import { PrismaClient, RecipeDietType, RecipeMealCategory } from '@prisma/client';

const nutritionBasis = 'Estimated per stated serving from IFCT 2017 and USDA FoodData Central reference ingredients. Oil, brands, preparation, and portion size can change nutrition.';

// Gluten policy: oats are naturally gluten-free but are commonly cross-contaminated and are not sold
// certified gluten-free here, so every oat-containing recipe is tagged GLUTEN (conservative/safe).
// Legumes/besan (gram flour) are naturally gluten-free and are NOT tagged.

const ingredients = [
  ['Poha (flattened rice)', 'g', 350, 6.7, 76.9, 1.1, 1.4], ['Rice, cooked', 'g', 130, 2.4, 28.2, 0.3, 0.4], ['Whole wheat flour', 'g', 340, 13.2, 72, 2.5, 10.7], ['Rolled oats', 'g', 379, 13.2, 67.7, 6.5, 10.1], ['Moong dal', 'g', 347, 24, 63, 1.2, 16.3], ['Rajma, cooked', 'g', 127, 8.7, 22.8, 0.5, 6.4], ['Chickpeas, cooked', 'g', 164, 8.9, 27.4, 2.6, 7.6], ['Toor dal, cooked', 'g', 116, 7.2, 20.1, 0.4, 7.9], ['Paneer', 'g', 265, 18.3, 1.2, 20.8, 0], ['Egg', 'g', 143, 12.6, 0.7, 9.5, 0], ['Chicken breast, cooked', 'g', 165, 31, 0, 3.6, 0], ['Fish, cooked', 'g', 128, 26, 0, 2.7, 0], ['Plain curd', 'g', 61, 3.5, 4.7, 3.3, 0], ['Banana', 'g', 89, 1.1, 22.8, 0.3, 2.6], ['Peanuts', 'g', 567, 25.8, 16.1, 49.2, 8.5], ['Potato', 'g', 77, 2, 17, 0.1, 2.2], ['Mixed vegetables', 'g', 65, 3.5, 12, 0.5, 3.5], ['Onion', 'g', 40, 1.1, 9.3, 0.1, 1.7], ['Tomato', 'g', 18, 0.9, 3.9, 0.2, 1.2], ['Cooking oil', 'ml', 884, 0, 0, 100, 0], ['Idli batter', 'g', 150, 4.5, 30, 0.8, 1.2], ['Coconut chutney', 'g', 265, 2.6, 11.5, 24, 6.7], ['Dates', 'g', 282, 2.5, 75, 0.4, 8], ['Soy milk', 'ml', 54, 3.3, 6.3, 1.8, 0.6],
  ['Besan (gram flour)', 'g', 387, 22, 58, 7, 11], ['Dosa batter', 'g', 150, 4.5, 30, 0.8, 1.2], ['Milk', 'ml', 62, 3.2, 4.8, 3.3, 0], ['Almonds', 'g', 579, 21, 22, 50, 12.5], ['Soya chunks (dry)', 'g', 345, 52, 33, 0.5, 13], ['Tofu', 'g', 76, 8, 1.9, 4.8, 0.3], ['Sweet potato', 'g', 86, 1.6, 20, 0.1, 3], ['Spinach', 'g', 23, 2.9, 3.6, 0.4, 2.2], ['Moong sprouts', 'g', 30, 3, 6, 0.2, 2],
  ['Apple', 'g', 52, 0.3, 14, 0.2, 2.4], ['Greek yogurt', 'g', 59, 10, 3.6, 0.4, 0], ['Cucumber', 'g', 15, 0.7, 3.6, 0.1, 0.5], ['Carrot', 'g', 41, 0.9, 9.6, 0.2, 2.8], ['Egg white', 'g', 52, 11, 0.7, 0.2, 0],
  ['Hung curd', 'g', 90, 9, 5, 4, 0], ['Moong dal, cooked', 'g', 105, 7, 19, 0.4, 7], ['Semolina (rava)', 'g', 360, 12.7, 72.8, 1.1, 3.9],
] as const;

type RecipeSeed = { slug: string; name: string; mealCategory: RecipeMealCategory; dietType: RecipeDietType; regionalCuisines: string[]; preparationMinutes: number; servingDescription: string; servingGrams?: number; calories: number; proteinGrams: number; carbohydrateGrams: number; fatGrams: number; fiberGrams: number; allergens: string[]; tags: string[]; preparationSteps: string[]; ingredients: Array<[string, number, string]> };

const recipes: RecipeSeed[] = [
  { slug: 'vegetable-poha', name: 'Vegetable Poha', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['Maharashtrian', 'Central Indian'], preparationMinutes: 20, servingDescription: '1 medium bowl', servingGrams: 280, calories: 480, proteinGrams: 12, carbohydrateGrams: 81, fatGrams: 12, fiberGrams: 7, allergens: ['PEANUT'], tags: ['quick', 'home-cooked'], preparationSteps: ['Rinse poha briefly and drain.', 'Saute onion, potato, and vegetables in measured oil.', 'Fold in poha, turmeric, lemon, and peanuts.'], ingredients: [['Poha (flattened rice)', 70, 'g'], ['Potato', 80, 'g'], ['Mixed vegetables', 100, 'g'], ['Peanuts', 10, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'idli-sambar-chutney', name: 'Idli with Sambar and Coconut Chutney', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['South Indian'], preparationMinutes: 30, servingDescription: '3 idli with sides', servingGrams: 330, calories: 360, proteinGrams: 12, carbohydrateGrams: 62, fatGrams: 8, fiberGrams: 8, allergens: [], tags: ['steamed', 'south-indian'], preparationSteps: ['Steam fermented batter in idli moulds.', 'Simmer vegetables and toor dal for sambar.', 'Serve with a measured spoon of coconut chutney.'], ingredients: [['Idli batter', 180, 'g'], ['Toor dal, cooked', 100, 'g'], ['Mixed vegetables', 100, 'g'], ['Coconut chutney', 25, 'g']] },
  { slug: 'vegetable-oats-upma', name: 'Vegetable Oats Upma', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['South Indian', 'Contemporary Indian'], preparationMinutes: 20, servingDescription: '1 medium bowl', servingGrams: 300, calories: 320, proteinGrams: 11, carbohydrateGrams: 48, fatGrams: 10, fiberGrams: 9, allergens: ['GLUTEN'], tags: ['high-fiber', 'quick'], preparationSteps: ['Toast oats until fragrant.', 'Saute vegetables in measured oil.', 'Add water, oats, and seasoning; cook until tender.'], ingredients: [['Rolled oats', 60, 'g'], ['Mixed vegetables', 150, 'g'], ['Onion', 40, 'g'], ['Cooking oil', 8, 'ml']] },
  { slug: 'moong-dal-chilla', name: 'Moong Dal Chilla', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 25, servingDescription: '2 medium chilla', servingGrams: 250, calories: 310, proteinGrams: 17, carbohydrateGrams: 42, fatGrams: 8, fiberGrams: 8, allergens: [], tags: ['high-protein', 'pan-cooked'], preparationSteps: ['Soak and blend moong dal with spices.', 'Fold in chopped onion and tomato.', 'Cook two thin chilla on a lightly oiled pan.'], ingredients: [['Moong dal', 75, 'g'], ['Onion', 50, 'g'], ['Tomato', 80, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'rajma-chawal', name: 'Rajma Chawal', mealCategory: 'LUNCH', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 35, servingDescription: '1 bowl rajma with rice', servingGrams: 430, calories: 520, proteinGrams: 19, carbohydrateGrams: 94, fatGrams: 8, fiberGrams: 15, allergens: [], tags: ['high-fiber', 'batch-cook'], preparationSteps: ['Simmer cooked rajma with tomato and spices.', 'Serve with measured cooked rice.', 'Finish with coriander and lemon.'], ingredients: [['Rajma, cooked', 220, 'g'], ['Rice, cooked', 180, 'g'], ['Tomato', 100, 'g'], ['Onion', 60, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'chole-roti', name: 'Chole with Roti', mealCategory: 'LUNCH', dietType: 'VEGAN', regionalCuisines: ['Punjabi', 'North Indian'], preparationMinutes: 35, servingDescription: '1 bowl chole with 2 roti', servingGrams: 380, calories: 500, proteinGrams: 20, carbohydrateGrams: 82, fatGrams: 10, fiberGrams: 16, allergens: ['GLUTEN'], tags: ['high-fiber', 'home-cooked'], preparationSteps: ['Simmer chickpeas in tomato-onion masala.', 'Roll and cook two whole-wheat roti.', 'Serve together.'], ingredients: [['Chickpeas, cooked', 220, 'g'], ['Whole wheat flour', 70, 'g'], ['Tomato', 100, 'g'], ['Onion', 60, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'paneer-bhurji-roti', name: 'Paneer Bhurji with Roti', mealCategory: 'DINNER', dietType: 'VEGETARIAN', regionalCuisines: ['North Indian'], preparationMinutes: 25, servingDescription: 'Paneer bhurji with 2 roti', servingGrams: 360, calories: 530, proteinGrams: 30, carbohydrateGrams: 54, fatGrams: 24, fiberGrams: 9, allergens: ['DAIRY', 'GLUTEN'], tags: ['high-protein', 'vegetarian'], preparationSteps: ['Saute onion and tomato in measured oil.', 'Crumble paneer into the masala and heat through.', 'Serve with two whole-wheat roti.'], ingredients: [['Paneer', 140, 'g'], ['Whole wheat flour', 70, 'g'], ['Onion', 60, 'g'], ['Tomato', 100, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'egg-bhurji-roti', name: 'Egg Bhurji with Roti', mealCategory: 'DINNER', dietType: 'NON_VEGETARIAN', regionalCuisines: ['North Indian', 'Parsi-inspired'], preparationMinutes: 20, servingDescription: '2 eggs with 2 roti', servingGrams: 340, calories: 470, proteinGrams: 25, carbohydrateGrams: 52, fatGrams: 18, fiberGrams: 8, allergens: ['EGG', 'GLUTEN'], tags: ['high-protein', 'quick'], preparationSteps: ['Saute onion and tomato in measured oil.', 'Scramble eggs gently into the masala.', 'Serve with two whole-wheat roti.'], ingredients: [['Egg', 110, 'g'], ['Whole wheat flour', 70, 'g'], ['Onion', 60, 'g'], ['Tomato', 100, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'chicken-rice-bowl', name: 'Chicken Rice Bowl', mealCategory: 'POST_WORKOUT', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 30, servingDescription: '1 bowl', servingGrams: 430, calories: 560, proteinGrams: 43, carbohydrateGrams: 68, fatGrams: 13, fiberGrams: 7, allergens: [], tags: ['high-protein', 'post-workout'], preparationSteps: ['Season and cook chicken until done.', 'Warm rice and sauteed vegetables.', 'Assemble into one bowl.'], ingredients: [['Chicken breast, cooked', 150, 'g'], ['Rice, cooked', 180, 'g'], ['Mixed vegetables', 150, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'fish-curry-rice', name: 'Fish Curry with Rice', mealCategory: 'DINNER', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Bengali', 'Coastal Indian'], preparationMinutes: 35, servingDescription: '1 curry bowl with rice', servingGrams: 420, calories: 490, proteinGrams: 34, carbohydrateGrams: 65, fatGrams: 11, fiberGrams: 5, allergens: ['FISH'], tags: ['coastal', 'high-protein'], preparationSteps: ['Cook fish gently in a spiced tomato curry.', 'Serve with measured cooked rice.', 'Add vegetables on the side.'], ingredients: [['Fish, cooked', 150, 'g'], ['Rice, cooked', 180, 'g'], ['Tomato', 120, 'g'], ['Onion', 60, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'banana-date-soy-smoothie', name: 'Banana Date Soy Smoothie', mealCategory: 'PRE_WORKOUT', dietType: 'VEGAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '1 large glass', servingGrams: 350, calories: 300, proteinGrams: 10, carbohydrateGrams: 57, fatGrams: 5, fiberGrams: 6, allergens: ['SOY'], tags: ['quick', 'pre-workout'], preparationSteps: ['Blend soy milk, banana, and dates until smooth.', 'Serve chilled or at room temperature.'], ingredients: [['Soy milk', 250, 'ml'], ['Banana', 120, 'g'], ['Dates', 25, 'g']] },
  { slug: 'curd-banana-peanut-bowl', name: 'Curd Banana Peanut Bowl', mealCategory: 'SNACK', dietType: 'VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '1 snack bowl', servingGrams: 300, calories: 340, proteinGrams: 14, carbohydrateGrams: 39, fatGrams: 15, fiberGrams: 5, allergens: ['DAIRY', 'PEANUT'], tags: ['quick', 'protein-snack'], preparationSteps: ['Add curd to a bowl.', 'Top with sliced banana and measured peanuts.', 'Serve immediately.'], ingredients: [['Plain curd', 200, 'g'], ['Banana', 100, 'g'], ['Peanuts', 20, 'g']] },
  { slug: 'besan-chilla', name: 'Besan Chilla', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 20, servingDescription: '2 chilla', servingGrams: 240, calories: 300, proteinGrams: 15, carbohydrateGrams: 38, fatGrams: 9, fiberGrams: 7, allergens: [], tags: ['high-protein', 'quick'], preparationSteps: ['Whisk besan with water and spices.', 'Fold in chopped onion and tomato.', 'Cook two thin chilla on a lightly oiled pan.'], ingredients: [['Besan (gram flour)', 70, 'g'], ['Onion', 40, 'g'], ['Tomato', 60, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'dosa-coconut-chutney', name: 'Dosa with Coconut Chutney', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['South Indian'], preparationMinutes: 20, servingDescription: '2 dosa with chutney', servingGrams: 290, calories: 320, proteinGrams: 9, carbohydrateGrams: 54, fatGrams: 8, fiberGrams: 5, allergens: [], tags: ['south-indian', 'home-cooked'], preparationSteps: ['Spread fermented batter thinly on a hot tava.', 'Crisp with a little oil.', 'Serve with a measured spoon of coconut chutney.'], ingredients: [['Dosa batter', 160, 'g'], ['Coconut chutney', 25, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'paneer-paratha', name: 'Paneer Paratha', mealCategory: 'BREAKFAST', dietType: 'VEGETARIAN', regionalCuisines: ['North Indian', 'Punjabi'], preparationMinutes: 25, servingDescription: '2 stuffed paratha', servingGrams: 260, calories: 420, proteinGrams: 18, carbohydrateGrams: 48, fatGrams: 17, fiberGrams: 7, allergens: ['DAIRY', 'GLUTEN'], tags: ['high-protein', 'home-cooked'], preparationSteps: ['Knead whole-wheat dough and rest.', 'Stuff with spiced crumbled paneer.', 'Roast two paratha with measured oil.'], ingredients: [['Whole wheat flour', 80, 'g'], ['Paneer', 60, 'g'], ['Onion', 30, 'g'], ['Cooking oil', 8, 'ml']] },
  { slug: 'banana-almond-oats-bowl', name: 'Banana Almond Oats Bowl', mealCategory: 'BREAKFAST', dietType: 'VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 10, servingDescription: '1 bowl', servingGrams: 350, calories: 380, proteinGrams: 14, carbohydrateGrams: 55, fatGrams: 12, fiberGrams: 9, allergens: ['DAIRY', 'TREE_NUT', 'GLUTEN'], tags: ['quick', 'high-fiber'], preparationSteps: ['Warm oats in milk until creamy.', 'Top with sliced banana and almonds.', 'Serve warm.'], ingredients: [['Rolled oats', 60, 'g'], ['Milk', 200, 'ml'], ['Banana', 80, 'g'], ['Almonds', 15, 'g']] },
  { slug: 'masala-omelette-toast', name: 'Masala Omelette with Toast', mealCategory: 'BREAKFAST', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 15, servingDescription: '2-egg omelette with 2 toast', servingGrams: 250, calories: 360, proteinGrams: 21, carbohydrateGrams: 30, fatGrams: 17, fiberGrams: 4, allergens: ['EGG', 'GLUTEN'], tags: ['high-protein', 'quick'], preparationSteps: ['Beat eggs with onion and spices.', 'Cook a soft omelette in measured oil.', 'Serve with two whole-wheat toast.'], ingredients: [['Egg', 120, 'g'], ['Whole wheat flour', 50, 'g'], ['Onion', 40, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'dal-rice-veg', name: 'Dal Rice with Vegetables', mealCategory: 'LUNCH', dietType: 'VEGAN', regionalCuisines: ['North Indian', 'Contemporary Indian'], preparationMinutes: 30, servingDescription: '1 bowl dal with rice', servingGrams: 440, calories: 480, proteinGrams: 17, carbohydrateGrams: 85, fatGrams: 7, fiberGrams: 12, allergens: [], tags: ['comfort', 'home-cooked'], preparationSteps: ['Simmer toor dal with turmeric and tempering.', 'Serve over measured cooked rice.', 'Add a side of cooked vegetables.'], ingredients: [['Toor dal, cooked', 150, 'g'], ['Rice, cooked', 180, 'g'], ['Mixed vegetables', 100, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'soya-chunk-curry-rice', name: 'Soya Chunk Curry with Rice', mealCategory: 'LUNCH', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 30, servingDescription: '1 curry bowl with rice', servingGrams: 400, calories: 520, proteinGrams: 30, carbohydrateGrams: 72, fatGrams: 10, fiberGrams: 12, allergens: ['SOY'], tags: ['high-protein', 'budget'], preparationSteps: ['Rehydrate soya chunks and squeeze dry.', 'Simmer in a spiced tomato-onion gravy.', 'Serve with measured cooked rice.'], ingredients: [['Soya chunks (dry)', 40, 'g'], ['Rice, cooked', 180, 'g'], ['Tomato', 100, 'g'], ['Onion', 60, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'paneer-veg-rice-bowl', name: 'Paneer Veg Rice Bowl', mealCategory: 'LUNCH', dietType: 'VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 25, servingDescription: '1 bowl', servingGrams: 430, calories: 560, proteinGrams: 26, carbohydrateGrams: 68, fatGrams: 20, fiberGrams: 8, allergens: ['DAIRY'], tags: ['high-protein', 'balanced'], preparationSteps: ['Saute paneer and vegetables in measured oil.', 'Fold through warm rice.', 'Season and serve.'], ingredients: [['Paneer', 100, 'g'], ['Rice, cooked', 180, 'g'], ['Mixed vegetables', 120, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'vegetable-pulao-raita', name: 'Vegetable Pulao with Raita', mealCategory: 'LUNCH', dietType: 'VEGETARIAN', regionalCuisines: ['North Indian'], preparationMinutes: 30, servingDescription: '1 plate pulao with raita', servingGrams: 420, calories: 500, proteinGrams: 14, carbohydrateGrams: 80, fatGrams: 14, fiberGrams: 8, allergens: ['DAIRY'], tags: ['one-pot', 'balanced'], preparationSteps: ['Cook rice with whole spices and vegetables.', 'Whisk curd into a simple raita.', 'Serve together.'], ingredients: [['Rice, cooked', 180, 'g'], ['Mixed vegetables', 150, 'g'], ['Plain curd', 80, 'g'], ['Cooking oil', 8, 'ml']] },
  { slug: 'chicken-curry-roti', name: 'Chicken Curry with Roti', mealCategory: 'LUNCH', dietType: 'NON_VEGETARIAN', regionalCuisines: ['North Indian'], preparationMinutes: 35, servingDescription: '1 curry bowl with 2 roti', servingGrams: 400, calories: 550, proteinGrams: 42, carbohydrateGrams: 55, fatGrams: 16, fiberGrams: 7, allergens: ['GLUTEN'], tags: ['high-protein', 'home-cooked'], preparationSteps: ['Cook chicken in a spiced tomato-onion gravy.', 'Roll and cook two whole-wheat roti.', 'Serve together.'], ingredients: [['Chicken breast, cooked', 150, 'g'], ['Whole wheat flour', 70, 'g'], ['Tomato', 100, 'g'], ['Onion', 60, 'g'], ['Cooking oil', 8, 'ml']] },
  { slug: 'dal-tadka-roti', name: 'Dal Tadka with Roti', mealCategory: 'DINNER', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 30, servingDescription: '1 bowl dal with 2 roti', servingGrams: 380, calories: 460, proteinGrams: 20, carbohydrateGrams: 68, fatGrams: 11, fiberGrams: 14, allergens: ['GLUTEN'], tags: ['high-fiber', 'comfort'], preparationSteps: ['Cook moong dal and finish with a tempering.', 'Roll and cook two whole-wheat roti.', 'Serve hot.'], ingredients: [['Moong dal', 70, 'g'], ['Whole wheat flour', 70, 'g'], ['Onion', 50, 'g'], ['Cooking oil', 8, 'ml']] },
  { slug: 'tofu-stir-fry-rice', name: 'Tofu Veg Stir Fry with Rice', mealCategory: 'DINNER', dietType: 'VEGAN', regionalCuisines: ['Indo-Chinese'], preparationMinutes: 25, servingDescription: '1 bowl', servingGrams: 420, calories: 480, proteinGrams: 22, carbohydrateGrams: 62, fatGrams: 14, fiberGrams: 8, allergens: ['SOY'], tags: ['high-protein', 'quick'], preparationSteps: ['Sear cubed tofu until golden.', 'Stir fry vegetables in measured oil.', 'Toss with warm rice and seasoning.'], ingredients: [['Tofu', 150, 'g'], ['Rice, cooked', 150, 'g'], ['Mixed vegetables', 150, 'g'], ['Cooking oil', 8, 'ml']] },
  { slug: 'chana-masala-rice', name: 'Chana Masala with Rice', mealCategory: 'DINNER', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 30, servingDescription: '1 bowl chana with rice', servingGrams: 430, calories: 500, proteinGrams: 18, carbohydrateGrams: 82, fatGrams: 9, fiberGrams: 14, allergens: [], tags: ['high-fiber', 'batch-cook'], preparationSteps: ['Simmer chickpeas in a spiced tomato masala.', 'Serve with measured cooked rice.', 'Finish with coriander.'], ingredients: [['Chickpeas, cooked', 200, 'g'], ['Rice, cooked', 150, 'g'], ['Tomato', 100, 'g'], ['Onion', 60, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'palak-paneer-roti', name: 'Palak Paneer with Roti', mealCategory: 'DINNER', dietType: 'VEGETARIAN', regionalCuisines: ['North Indian'], preparationMinutes: 30, servingDescription: 'Palak paneer with 2 roti', servingGrams: 380, calories: 520, proteinGrams: 26, carbohydrateGrams: 50, fatGrams: 24, fiberGrams: 9, allergens: ['DAIRY', 'GLUTEN'], tags: ['high-protein', 'vegetarian'], preparationSteps: ['Blanch and puree spinach.', 'Simmer paneer cubes in the spinach gravy.', 'Serve with two whole-wheat roti.'], ingredients: [['Paneer', 120, 'g'], ['Spinach', 150, 'g'], ['Whole wheat flour', 70, 'g'], ['Cooking oil', 8, 'ml']] },
  { slug: 'grilled-chicken-sweet-potato', name: 'Grilled Chicken with Sweet Potato', mealCategory: 'DINNER', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 30, servingDescription: '1 plate', servingGrams: 450, calories: 500, proteinGrams: 45, carbohydrateGrams: 45, fatGrams: 14, fiberGrams: 7, allergens: [], tags: ['high-protein', 'balanced'], preparationSteps: ['Season and grill chicken breast.', 'Roast sweet potato wedges.', 'Serve with a side of vegetables.'], ingredients: [['Chicken breast, cooked', 150, 'g'], ['Sweet potato', 200, 'g'], ['Mixed vegetables', 100, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'sprouts-chaat', name: 'Sprouts Potato Chaat', mealCategory: 'SNACK', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 10, servingDescription: '1 bowl', servingGrams: 350, calories: 190, proteinGrams: 7, carbohydrateGrams: 32, fatGrams: 4, fiberGrams: 7, allergens: [], tags: ['high-fiber', 'vegan'], preparationSteps: ['Steam moong sprouts and boiled potato cubes.', 'Toss with chopped onion, tomato, lemon, and spices in a little oil.', 'Serve fresh.'], ingredients: [['Moong sprouts', 150, 'g'], ['Potato', 100, 'g'], ['Onion', 40, 'g'], ['Tomato', 60, 'g'], ['Cooking oil', 3, 'ml']] },
  { slug: 'roasted-chana-almonds', name: 'Roasted Chana and Almonds', mealCategory: 'SNACK', dietType: 'VEGAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '1 small bowl', servingGrams: 140, calories: 260, proteinGrams: 13, carbohydrateGrams: 30, fatGrams: 11, fiberGrams: 9, allergens: ['TREE_NUT'], tags: ['quick', 'protein-snack'], preparationSteps: ['Combine roasted chickpeas and almonds.', 'Season lightly.', 'Serve as a portioned snack.'], ingredients: [['Chickpeas, cooked', 120, 'g'], ['Almonds', 20, 'g']] },
  { slug: 'boiled-egg-snack', name: 'Boiled Egg Snack', mealCategory: 'SNACK', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 10, servingDescription: '2 boiled eggs', servingGrams: 140, calories: 180, proteinGrams: 15, carbohydrateGrams: 3, fatGrams: 12, fiberGrams: 0, allergens: ['EGG'], tags: ['high-protein', 'quick'], preparationSteps: ['Boil eggs to firm.', 'Peel and season with pepper and salt.', 'Serve with sliced onion.'], ingredients: [['Egg', 120, 'g'], ['Onion', 20, 'g']] },
  { slug: 'peanut-banana-toast', name: 'Peanut Banana Toast', mealCategory: 'PRE_WORKOUT', dietType: 'VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '2 toast', servingGrams: 180, calories: 300, proteinGrams: 11, carbohydrateGrams: 42, fatGrams: 11, fiberGrams: 6, allergens: ['GLUTEN', 'PEANUT'], tags: ['quick', 'pre-workout'], preparationSteps: ['Toast two whole-wheat slices.', 'Spread peanut butter and top with banana.', 'Serve immediately.'], ingredients: [['Whole wheat flour', 60, 'g'], ['Peanuts', 20, 'g'], ['Banana', 80, 'g']] },
  { slug: 'curd-fruit-cup', name: 'Curd Fruit Cup', mealCategory: 'PRE_WORKOUT', dietType: 'VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '1 cup', servingGrams: 250, calories: 220, proteinGrams: 10, carbohydrateGrams: 32, fatGrams: 6, fiberGrams: 4, allergens: ['DAIRY'], tags: ['quick', 'pre-workout'], preparationSteps: ['Add curd to a cup.', 'Top with banana and chopped dates.', 'Serve chilled.'], ingredients: [['Plain curd', 150, 'g'], ['Banana', 80, 'g'], ['Dates', 20, 'g']] },
  { slug: 'paneer-protein-bowl', name: 'Paneer Protein Bowl', mealCategory: 'POST_WORKOUT', dietType: 'VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 20, servingDescription: '1 bowl', servingGrams: 400, calories: 520, proteinGrams: 32, carbohydrateGrams: 55, fatGrams: 18, fiberGrams: 6, allergens: ['DAIRY'], tags: ['high-protein', 'post-workout'], preparationSteps: ['Saute paneer with light spices.', 'Warm rice and vegetables.', 'Assemble into one bowl.'], ingredients: [['Paneer', 120, 'g'], ['Rice, cooked', 150, 'g'], ['Mixed vegetables', 100, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'soy-oats-protein-shake', name: 'Soy Oats Protein Shake', mealCategory: 'POST_WORKOUT', dietType: 'VEGAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '1 large glass', servingGrams: 440, calories: 360, proteinGrams: 18, carbohydrateGrams: 55, fatGrams: 8, fiberGrams: 8, allergens: ['SOY', 'GLUTEN'], tags: ['quick', 'post-workout'], preparationSteps: ['Blend soy milk with oats, banana, and dates.', 'Blend until smooth.', 'Serve immediately.'], ingredients: [['Soy milk', 300, 'ml'], ['Rolled oats', 40, 'g'], ['Banana', 80, 'g'], ['Dates', 20, 'g']] },
  { slug: 'fruit-oats-bowl', name: 'Fruit and Oats Bowl', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 10, servingDescription: '1 bowl', servingGrams: 380, calories: 360, proteinGrams: 12, carbohydrateGrams: 62, fatGrams: 7, fiberGrams: 9, allergens: ['SOY', 'GLUTEN'], tags: ['high-carb', 'quick', 'low-fat'], preparationSteps: ['Soak oats in soy milk until soft.', 'Top with sliced banana and apple.', 'Serve chilled.'], ingredients: [['Rolled oats', 50, 'g'], ['Banana', 100, 'g'], ['Apple', 80, 'g'], ['Soy milk', 150, 'ml']] },
  { slug: 'lemon-chickpea-rice', name: 'Lemon Chickpea Rice', mealCategory: 'LUNCH', dietType: 'VEGAN', regionalCuisines: ['South Indian', 'Contemporary Indian'], preparationMinutes: 25, servingDescription: '1 bowl', servingGrams: 400, calories: 450, proteinGrams: 16, carbohydrateGrams: 78, fatGrams: 8, fiberGrams: 10, allergens: [], tags: ['high-carb', 'low-fat', 'batch-cook'], preparationSteps: ['Temper spices and add cooked chickpeas.', 'Fold in rice, lemon, and vegetables.', 'Season and serve.'], ingredients: [['Rice, cooked', 180, 'g'], ['Chickpeas, cooked', 100, 'g'], ['Mixed vegetables', 80, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'vegetable-khichdi', name: 'Vegetable Khichdi', mealCategory: 'DINNER', dietType: 'VEGAN', regionalCuisines: ['North Indian', 'Contemporary Indian'], preparationMinutes: 30, servingDescription: '1 bowl', servingGrams: 400, calories: 420, proteinGrams: 14, carbohydrateGrams: 73, fatGrams: 7, fiberGrams: 11, allergens: [], tags: ['comfort', 'low-fat', 'high-fiber'], preparationSteps: ['Pressure-cook rice and moong dal with turmeric.', 'Stir in vegetables and a light tempering.', 'Serve hot.'], ingredients: [['Rice, cooked', 150, 'g'], ['Moong dal, cooked', 100, 'g'], ['Mixed vegetables', 100, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'tofu-scramble-toast', name: 'Tofu Scramble with Toast', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 15, servingDescription: 'Scramble with 2 toast', servingGrams: 250, calories: 320, proteinGrams: 20, carbohydrateGrams: 34, fatGrams: 12, fiberGrams: 6, allergens: ['SOY', 'GLUTEN'], tags: ['high-protein', 'quick'], preparationSteps: ['Crumble tofu and saute with turmeric and onion.', 'Toast two whole-wheat slices.', 'Serve together.'], ingredients: [['Tofu', 150, 'g'], ['Whole wheat flour', 50, 'g'], ['Onion', 40, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'rajma-rice-power-bowl', name: 'Rajma Rice Power Bowl', mealCategory: 'POST_WORKOUT', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 20, servingDescription: '1 bowl', servingGrams: 360, calories: 480, proteinGrams: 20, carbohydrateGrams: 82, fatGrams: 8, fiberGrams: 13, allergens: [], tags: ['high-protein', 'high-carb', 'post-workout'], preparationSteps: ['Warm cooked rajma and rice together.', 'Season with spices and lemon.', 'Serve immediately.'], ingredients: [['Rajma, cooked', 180, 'g'], ['Rice, cooked', 150, 'g'], ['Cooking oil', 5, 'ml']] },
  { slug: 'greek-yogurt-fruit-bowl', name: 'Greek Yogurt Fruit Bowl', mealCategory: 'BREAKFAST', dietType: 'VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '1 bowl', servingGrams: 310, calories: 310, proteinGrams: 22, carbohydrateGrams: 44, fatGrams: 5, fiberGrams: 5, allergens: ['DAIRY', 'GLUTEN'], tags: ['high-protein', 'low-fat', 'quick'], preparationSteps: ['Add thick yogurt to a bowl.', 'Top with banana and oats.', 'Serve chilled.'], ingredients: [['Greek yogurt', 200, 'g'], ['Banana', 80, 'g'], ['Rolled oats', 30, 'g']] },
  { slug: 'hung-curd-protein-bowl', name: 'Hung Curd Protein Bowl', mealCategory: 'SNACK', dietType: 'VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '1 small bowl', servingGrams: 260, calories: 205, proteinGrams: 16, carbohydrateGrams: 20, fatGrams: 7, fiberGrams: 2, allergens: ['DAIRY'], tags: ['high-protein', 'protein-snack'], preparationSteps: ['Spoon thick hung curd into a bowl.', 'Top with chopped apple.', 'Serve fresh.'], ingredients: [['Hung curd', 180, 'g'], ['Apple', 80, 'g']] },
  { slug: 'paneer-veg-salad', name: 'Paneer Veg Salad', mealCategory: 'LUNCH', dietType: 'VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 15, servingDescription: '1 plate', servingGrams: 330, calories: 370, proteinGrams: 26, carbohydrateGrams: 30, fatGrams: 16, fiberGrams: 6, allergens: ['DAIRY'], tags: ['high-protein', 'balanced'], preparationSteps: ['Lightly sear paneer cubes.', 'Toss with chopped vegetables, cucumber, and carrot.', 'Dress with lemon and spices.'], ingredients: [['Paneer', 90, 'g'], ['Mixed vegetables', 120, 'g'], ['Cucumber', 60, 'g'], ['Carrot', 50, 'g'], ['Cooking oil', 5, 'ml']] },
  { slug: 'egg-white-bhurji-toast', name: 'Egg White Bhurji with Toast', mealCategory: 'BREAKFAST', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 15, servingDescription: 'Bhurji with 2 toast', servingGrams: 270, calories: 300, proteinGrams: 24, carbohydrateGrams: 32, fatGrams: 8, fiberGrams: 4, allergens: ['EGG', 'GLUTEN'], tags: ['high-protein', 'low-fat', 'quick'], preparationSteps: ['Scramble egg whites with onion and spices.', 'Toast two whole-wheat slices.', 'Serve together.'], ingredients: [['Egg white', 180, 'g'], ['Whole wheat flour', 50, 'g'], ['Onion', 40, 'g'], ['Cooking oil', 4, 'ml']] },
  { slug: 'egg-veg-pulao', name: 'Egg Veg Pulao', mealCategory: 'LUNCH', dietType: 'NON_VEGETARIAN', regionalCuisines: ['North Indian'], preparationMinutes: 30, servingDescription: '1 plate', servingGrams: 400, calories: 490, proteinGrams: 22, carbohydrateGrams: 70, fatGrams: 14, fiberGrams: 7, allergens: ['EGG'], tags: ['high-protein', 'balanced'], preparationSteps: ['Cook rice with whole spices and vegetables.', 'Fold in chopped boiled egg.', 'Serve hot.'], ingredients: [['Rice, cooked', 180, 'g'], ['Egg', 100, 'g'], ['Mixed vegetables', 100, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'chicken-salad-bowl', name: 'Chicken Salad Bowl', mealCategory: 'LUNCH', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 20, servingDescription: '1 bowl', servingGrams: 340, calories: 400, proteinGrams: 42, carbohydrateGrams: 30, fatGrams: 12, fiberGrams: 6, allergens: [], tags: ['high-protein', 'low-carb', 'balanced'], preparationSteps: ['Grill and slice chicken breast.', 'Toss with vegetables, cucumber, and a light dressing.', 'Serve fresh.'], ingredients: [['Chicken breast, cooked', 150, 'g'], ['Mixed vegetables', 120, 'g'], ['Cucumber', 60, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'grilled-fish-rice-veg', name: 'Grilled Fish with Rice and Veg', mealCategory: 'DINNER', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Coastal Indian', 'Contemporary Indian'], preparationMinutes: 30, servingDescription: '1 plate', servingGrams: 400, calories: 470, proteinGrams: 34, carbohydrateGrams: 60, fatGrams: 10, fiberGrams: 5, allergens: ['FISH'], tags: ['high-protein', 'low-fat', 'balanced'], preparationSteps: ['Season and grill the fish.', 'Warm rice and saute vegetables.', 'Plate together.'], ingredients: [['Fish, cooked', 150, 'g'], ['Rice, cooked', 170, 'g'], ['Mixed vegetables', 80, 'g'], ['Cooking oil', 5, 'ml']] },
  { slug: 'tofu-fried-rice', name: 'Tofu Fried Rice', mealCategory: 'DINNER', dietType: 'VEGAN', regionalCuisines: ['Indo-Chinese'], preparationMinutes: 20, servingDescription: '1 bowl', servingGrams: 437, calories: 490, proteinGrams: 20, carbohydrateGrams: 69, fatGrams: 15, fiberGrams: 4, allergens: ['SOY'], tags: ['high-protein', 'low-fiber', 'quick'], preparationSteps: ['Sear cubed tofu until golden.', 'Toss cooked rice with vegetables in measured oil.', 'Fold in tofu and seasoning.'], ingredients: [['Tofu', 150, 'g'], ['Rice, cooked', 200, 'g'], ['Mixed vegetables', 80, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'soy-chunk-fried-rice', name: 'Soya Chunk Fried Rice', mealCategory: 'DINNER', dietType: 'VEGAN', regionalCuisines: ['Indo-Chinese'], preparationMinutes: 25, servingDescription: '1 bowl', servingGrams: 357, calories: 495, proteinGrams: 24, carbohydrateGrams: 80, fatGrams: 8, fiberGrams: 8, allergens: ['SOY'], tags: ['high-protein', 'budget'], preparationSteps: ['Rehydrate soya chunks and chop.', 'Stir fry with vegetables and cooked rice in measured oil.', 'Season and serve.'], ingredients: [['Soya chunks (dry)', 30, 'g'], ['Rice, cooked', 200, 'g'], ['Mixed vegetables', 80, 'g'], ['Onion', 40, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'tofu-bhurji-rice', name: 'Tofu Bhurji with Rice', mealCategory: 'DINNER', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 20, servingDescription: '1 bowl', servingGrams: 466, calories: 435, proteinGrams: 18, carbohydrateGrams: 61, fatGrams: 15, fiberGrams: 3, allergens: ['SOY'], tags: ['high-protein', 'low-fiber'], preparationSteps: ['Crumble and saute tofu with onion, tomato, and turmeric.', 'Serve over measured cooked rice.', 'Finish with coriander.'], ingredients: [['Tofu', 150, 'g'], ['Rice, cooked', 180, 'g'], ['Tomato', 80, 'g'], ['Onion', 50, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'paneer-jeera-rice', name: 'Paneer Jeera Rice', mealCategory: 'DINNER', dietType: 'VEGETARIAN', regionalCuisines: ['North Indian'], preparationMinutes: 25, servingDescription: '1 plate', servingGrams: 405, calories: 585, proteinGrams: 23, carbohydrateGrams: 71, fatGrams: 23, fiberGrams: 4, allergens: ['DAIRY'], tags: ['high-protein', 'low-fiber'], preparationSteps: ['Temper cumin and saute paneer cubes.', 'Fold in cooked rice and vegetables.', 'Season and serve.'], ingredients: [['Paneer', 80, 'g'], ['Rice, cooked', 200, 'g'], ['Mixed vegetables', 80, 'g'], ['Onion', 40, 'g'], ['Cooking oil', 5, 'ml']] },
  { slug: 'curd-rice', name: 'Curd Rice', mealCategory: 'DINNER', dietType: 'VEGETARIAN', regionalCuisines: ['South Indian'], preparationMinutes: 15, servingDescription: '1 bowl', servingGrams: 413, calories: 420, proteinGrams: 11, carbohydrateGrams: 73, fatGrams: 9, fiberGrams: 2, allergens: ['DAIRY'], tags: ['low-fiber', 'comfort'], preparationSteps: ['Mix cooked rice with whisked curd.', 'Add a light tempering and grated carrot.', 'Serve chilled or at room temperature.'], ingredients: [['Rice, cooked', 220, 'g'], ['Plain curd', 150, 'g'], ['Carrot', 40, 'g'], ['Cooking oil', 3, 'ml']] },
  { slug: 'egg-curry-rice', name: 'Egg Curry with Rice', mealCategory: 'DINNER', dietType: 'NON_VEGETARIAN', regionalCuisines: ['North Indian'], preparationMinutes: 30, servingDescription: '1 curry bowl with rice', servingGrams: 477, calories: 525, proteinGrams: 22, carbohydrateGrams: 61, fatGrams: 20, fiberGrams: 3, allergens: ['EGG'], tags: ['high-protein', 'low-fiber'], preparationSteps: ['Simmer boiled eggs in a spiced tomato-onion gravy.', 'Serve with measured cooked rice.', 'Finish with coriander.'], ingredients: [['Egg', 130, 'g'], ['Rice, cooked', 180, 'g'], ['Tomato', 100, 'g'], ['Onion', 60, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'chicken-fried-rice', name: 'Chicken Fried Rice', mealCategory: 'DINNER', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Indo-Chinese'], preparationMinutes: 25, servingDescription: '1 bowl', servingGrams: 447, calories: 590, proteinGrams: 45, carbohydrateGrams: 70, fatGrams: 12, fiberGrams: 4, allergens: [], tags: ['high-protein', 'low-fiber'], preparationSteps: ['Stir fry cooked chicken with vegetables.', 'Toss in cooked rice and seasoning.', 'Serve hot.'], ingredients: [['Chicken breast, cooked', 120, 'g'], ['Rice, cooked', 200, 'g'], ['Mixed vegetables', 80, 'g'], ['Onion', 40, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'tofu-banana-protein-shake', name: 'Tofu Banana Protein Shake', mealCategory: 'POST_WORKOUT', dietType: 'VEGAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '1 large glass', servingGrams: 455, calories: 325, proteinGrams: 16, carbohydrateGrams: 50, fatGrams: 8, fiberGrams: 5, allergens: ['SOY'], tags: ['high-protein', 'quick', 'post-workout'], preparationSteps: ['Blend soy milk, tofu, banana, and dates.', 'Blend until smooth.', 'Serve immediately.'], ingredients: [['Soy milk', 300, 'ml'], ['Tofu', 60, 'g'], ['Banana', 80, 'g'], ['Dates', 15, 'g']] },
  { slug: 'rava-upma', name: 'Rava Upma', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['South Indian'], preparationMinutes: 20, servingDescription: '1 medium bowl', servingGrams: 208, calories: 370, proteinGrams: 12, carbohydrateGrams: 59, fatGrams: 9, fiberGrams: 7, allergens: ['GLUTEN'], tags: ['quick', 'home-cooked'], preparationSteps: ['Roast semolina until fragrant.', 'Saute vegetables and onion in measured oil.', 'Add water and semolina; cook until fluffy.'], ingredients: [['Semolina (rava)', 60, 'g'], ['Mixed vegetables', 100, 'g'], ['Onion', 40, 'g'], ['Cooking oil', 8, 'ml']] },
];

// Exposed for tests and the ingredient-level reconciliation utility (pure data, no Prisma).
export const recipeCatalogSeeds: readonly RecipeSeed[] = recipes;
export const ingredientCatalogSeeds = ingredients;
export type { RecipeSeed };

export async function seedRecipeCatalog(prisma: PrismaClient): Promise<void> {
  for (const [name, standardUnit, caloriesPer100g, proteinGramsPer100g, carbohydrateGramsPer100g, fatGramsPer100g, fiberGramsPer100g] of ingredients) {
    await prisma.ingredient.upsert({ where: { name }, update: { standardUnit, caloriesPer100g, proteinGramsPer100g, carbohydrateGramsPer100g, fatGramsPer100g, fiberGramsPer100g, nutritionSource: 'IFCT 2017 and USDA FoodData Central reference values' }, create: { name, standardUnit, caloriesPer100g, proteinGramsPer100g, carbohydrateGramsPer100g, fatGramsPer100g, fiberGramsPer100g, nutritionSource: 'IFCT 2017 and USDA FoodData Central reference values' } });
  }
  for (const recipe of recipes) {
    const { ingredients: recipeIngredients, ...recipeData } = recipe;
    await prisma.recipe.upsert({
      where: { slug: recipe.slug },
      update: { ...recipeData, nutritionBasis, ingredients: { deleteMany: {}, create: recipeIngredients.map(([name, quantity, unit]) => ({ quantity, unit, ingredient: { connect: { name } } })) } },
      create: { ...recipeData, nutritionBasis, ingredients: { create: recipeIngredients.map(([name, quantity, unit]) => ({ quantity, unit, ingredient: { connect: { name } } })) } },
    });
  }
}