import { PrismaClient, RecipeDietType, RecipeMealCategory } from '@prisma/client';

const nutritionBasis = 'Estimated per stated serving from IFCT 2017 and USDA FoodData Central reference ingredients. Oil, brands, preparation, and portion size can change nutrition.';

const ingredients = [
  ['Poha (flattened rice)', 'g', 350, 6.7, 76.9, 1.1, 1.4], ['Rice, cooked', 'g', 130, 2.4, 28.2, 0.3, 0.4], ['Whole wheat flour', 'g', 340, 13.2, 72, 2.5, 10.7], ['Rolled oats', 'g', 379, 13.2, 67.7, 6.5, 10.1], ['Moong dal', 'g', 347, 24, 63, 1.2, 16.3], ['Rajma, cooked', 'g', 127, 8.7, 22.8, 0.5, 6.4], ['Chickpeas, cooked', 'g', 164, 8.9, 27.4, 2.6, 7.6], ['Toor dal, cooked', 'g', 116, 7.2, 20.1, 0.4, 7.9], ['Paneer', 'g', 265, 18.3, 1.2, 20.8, 0], ['Egg', 'g', 143, 12.6, 0.7, 9.5, 0], ['Chicken breast, cooked', 'g', 165, 31, 0, 3.6, 0], ['Fish, cooked', 'g', 128, 26, 0, 2.7, 0], ['Plain curd', 'g', 61, 3.5, 4.7, 3.3, 0], ['Banana', 'g', 89, 1.1, 22.8, 0.3, 2.6], ['Peanuts', 'g', 567, 25.8, 16.1, 49.2, 8.5], ['Potato', 'g', 77, 2, 17, 0.1, 2.2], ['Mixed vegetables', 'g', 65, 3.5, 12, 0.5, 3.5], ['Onion', 'g', 40, 1.1, 9.3, 0.1, 1.7], ['Tomato', 'g', 18, 0.9, 3.9, 0.2, 1.2], ['Cooking oil', 'ml', 884, 0, 0, 100, 0], ['Idli batter', 'g', 150, 4.5, 30, 0.8, 1.2], ['Coconut chutney', 'g', 265, 2.6, 11.5, 24, 6.7], ['Dates', 'g', 282, 2.5, 75, 0.4, 8], ['Soy milk', 'ml', 54, 3.3, 6.3, 1.8, 0.6],
] as const;

type RecipeSeed = { slug: string; name: string; mealCategory: RecipeMealCategory; dietType: RecipeDietType; regionalCuisines: string[]; preparationMinutes: number; servingDescription: string; servingGrams?: number; calories: number; proteinGrams: number; carbohydrateGrams: number; fatGrams: number; fiberGrams: number; allergens: string[]; tags: string[]; preparationSteps: string[]; ingredients: Array<[string, number, string]> };

const recipes: RecipeSeed[] = [
  { slug: 'vegetable-poha', name: 'Vegetable Poha', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['Maharashtrian', 'Central Indian'], preparationMinutes: 20, servingDescription: '1 medium bowl', servingGrams: 280, calories: 330, proteinGrams: 7, carbohydrateGrams: 56, fatGrams: 9, fiberGrams: 6, allergens: ['PEANUT'], tags: ['quick', 'home-cooked'], preparationSteps: ['Rinse poha briefly and drain.', 'Saute onion, potato, and vegetables in measured oil.', 'Fold in poha, turmeric, lemon, and peanuts.'], ingredients: [['Poha (flattened rice)', 70, 'g'], ['Potato', 80, 'g'], ['Mixed vegetables', 100, 'g'], ['Peanuts', 12, 'g'], ['Cooking oil', 8, 'ml']] },
  { slug: 'idli-sambar-chutney', name: 'Idli with Sambar and Coconut Chutney', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['South Indian'], preparationMinutes: 30, servingDescription: '3 idli with sides', servingGrams: 330, calories: 360, proteinGrams: 12, carbohydrateGrams: 62, fatGrams: 8, fiberGrams: 8, allergens: [], tags: ['steamed', 'south-indian'], preparationSteps: ['Steam fermented batter in idli moulds.', 'Simmer vegetables and toor dal for sambar.', 'Serve with a measured spoon of coconut chutney.'], ingredients: [['Idli batter', 180, 'g'], ['Toor dal, cooked', 100, 'g'], ['Mixed vegetables', 100, 'g'], ['Coconut chutney', 25, 'g']] },
  { slug: 'vegetable-oats-upma', name: 'Vegetable Oats Upma', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['South Indian', 'Contemporary Indian'], preparationMinutes: 20, servingDescription: '1 medium bowl', servingGrams: 300, calories: 320, proteinGrams: 11, carbohydrateGrams: 48, fatGrams: 10, fiberGrams: 9, allergens: ['GLUTEN'], tags: ['high-fiber', 'quick'], preparationSteps: ['Toast oats until fragrant.', 'Saute vegetables in measured oil.', 'Add water, oats, and seasoning; cook until tender.'], ingredients: [['Rolled oats', 60, 'g'], ['Mixed vegetables', 150, 'g'], ['Onion', 40, 'g'], ['Cooking oil', 8, 'ml']] },
  { slug: 'moong-dal-chilla', name: 'Moong Dal Chilla', mealCategory: 'BREAKFAST', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 25, servingDescription: '2 medium chilla', servingGrams: 250, calories: 310, proteinGrams: 17, carbohydrateGrams: 42, fatGrams: 8, fiberGrams: 8, allergens: [], tags: ['high-protein', 'pan-cooked'], preparationSteps: ['Soak and blend moong dal with spices.', 'Fold in chopped onion and tomato.', 'Cook two thin chilla on a lightly oiled pan.'], ingredients: [['Moong dal', 75, 'g'], ['Onion', 50, 'g'], ['Tomato', 80, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'rajma-chawal', name: 'Rajma Chawal', mealCategory: 'LUNCH', dietType: 'VEGAN', regionalCuisines: ['North Indian'], preparationMinutes: 35, servingDescription: '1 bowl rajma with rice', servingGrams: 430, calories: 520, proteinGrams: 19, carbohydrateGrams: 94, fatGrams: 8, fiberGrams: 15, allergens: [], tags: ['high-fiber', 'batch-cook'], preparationSteps: ['Simmer cooked rajma with tomato and spices.', 'Serve with measured cooked rice.', 'Finish with coriander and lemon.'], ingredients: [['Rajma, cooked', 220, 'g'], ['Rice, cooked', 180, 'g'], ['Tomato', 100, 'g'], ['Onion', 60, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'chole-roti', name: 'Chole with Roti', mealCategory: 'LUNCH', dietType: 'VEGAN', regionalCuisines: ['Punjabi', 'North Indian'], preparationMinutes: 35, servingDescription: '1 bowl chole with 2 roti', servingGrams: 380, calories: 500, proteinGrams: 20, carbohydrateGrams: 82, fatGrams: 10, fiberGrams: 16, allergens: ['GLUTEN'], tags: ['high-fiber', 'home-cooked'], preparationSteps: ['Simmer chickpeas in tomato-onion masala.', 'Roll and cook two whole-wheat roti.', 'Serve together.'], ingredients: [['Chickpeas, cooked', 220, 'g'], ['Whole wheat flour', 70, 'g'], ['Tomato', 100, 'g'], ['Onion', 60, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'paneer-bhurji-roti', name: 'Paneer Bhurji with Roti', mealCategory: 'DINNER', dietType: 'VEGETARIAN', regionalCuisines: ['North Indian'], preparationMinutes: 25, servingDescription: 'Paneer bhurji with 2 roti', servingGrams: 360, calories: 530, proteinGrams: 30, carbohydrateGrams: 54, fatGrams: 24, fiberGrams: 9, allergens: ['DAIRY', 'GLUTEN'], tags: ['high-protein', 'vegetarian'], preparationSteps: ['Saute onion and tomato in measured oil.', 'Crumble paneer into the masala and heat through.', 'Serve with two whole-wheat roti.'], ingredients: [['Paneer', 140, 'g'], ['Whole wheat flour', 70, 'g'], ['Onion', 60, 'g'], ['Tomato', 100, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'egg-bhurji-roti', name: 'Egg Bhurji with Roti', mealCategory: 'DINNER', dietType: 'NON_VEGETARIAN', regionalCuisines: ['North Indian', 'Parsi-inspired'], preparationMinutes: 20, servingDescription: '2 eggs with 2 roti', servingGrams: 340, calories: 470, proteinGrams: 25, carbohydrateGrams: 52, fatGrams: 18, fiberGrams: 8, allergens: ['EGG', 'GLUTEN'], tags: ['high-protein', 'quick'], preparationSteps: ['Saute onion and tomato in measured oil.', 'Scramble eggs gently into the masala.', 'Serve with two whole-wheat roti.'], ingredients: [['Egg', 110, 'g'], ['Whole wheat flour', 70, 'g'], ['Onion', 60, 'g'], ['Tomato', 100, 'g'], ['Cooking oil', 6, 'ml']] },
  { slug: 'chicken-rice-bowl', name: 'Chicken Rice Bowl', mealCategory: 'POST_WORKOUT', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 30, servingDescription: '1 bowl', servingGrams: 430, calories: 560, proteinGrams: 43, carbohydrateGrams: 68, fatGrams: 13, fiberGrams: 7, allergens: [], tags: ['high-protein', 'post-workout'], preparationSteps: ['Season and cook chicken until done.', 'Warm rice and sauteed vegetables.', 'Assemble into one bowl.'], ingredients: [['Chicken breast, cooked', 150, 'g'], ['Rice, cooked', 180, 'g'], ['Mixed vegetables', 150, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'fish-curry-rice', name: 'Fish Curry with Rice', mealCategory: 'DINNER', dietType: 'NON_VEGETARIAN', regionalCuisines: ['Bengali', 'Coastal Indian'], preparationMinutes: 35, servingDescription: '1 curry bowl with rice', servingGrams: 420, calories: 490, proteinGrams: 34, carbohydrateGrams: 65, fatGrams: 11, fiberGrams: 5, allergens: ['FISH'], tags: ['coastal', 'high-protein'], preparationSteps: ['Cook fish gently in a spiced tomato curry.', 'Serve with measured cooked rice.', 'Add vegetables on the side.'], ingredients: [['Fish, cooked', 150, 'g'], ['Rice, cooked', 180, 'g'], ['Tomato', 120, 'g'], ['Onion', 60, 'g'], ['Cooking oil', 7, 'ml']] },
  { slug: 'banana-date-soy-smoothie', name: 'Banana Date Soy Smoothie', mealCategory: 'PRE_WORKOUT', dietType: 'VEGAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '1 large glass', servingGrams: 350, calories: 300, proteinGrams: 10, carbohydrateGrams: 57, fatGrams: 5, fiberGrams: 6, allergens: ['SOY'], tags: ['quick', 'pre-workout'], preparationSteps: ['Blend soy milk, banana, and dates until smooth.', 'Serve chilled or at room temperature.'], ingredients: [['Soy milk', 250, 'ml'], ['Banana', 120, 'g'], ['Dates', 25, 'g']] },
  { slug: 'curd-banana-peanut-bowl', name: 'Curd Banana Peanut Bowl', mealCategory: 'SNACK', dietType: 'VEGETARIAN', regionalCuisines: ['Contemporary Indian'], preparationMinutes: 5, servingDescription: '1 snack bowl', servingGrams: 300, calories: 340, proteinGrams: 14, carbohydrateGrams: 39, fatGrams: 15, fiberGrams: 5, allergens: ['DAIRY', 'PEANUT'], tags: ['quick', 'protein-snack'], preparationSteps: ['Add curd to a bowl.', 'Top with sliced banana and measured peanuts.', 'Serve immediately.'], ingredients: [['Plain curd', 200, 'g'], ['Banana', 100, 'g'], ['Peanuts', 20, 'g']] },
];

export async function seedRecipeCatalog(prisma: PrismaClient): Promise<void> {
  for (const [name, standardUnit, caloriesPer100g, proteinGramsPer100g, carbohydrateGramsPer100g, fatGramsPer100g, fiberGramsPer100g] of ingredients) {
    await prisma.ingredient.upsert({ where: { name }, update: { standardUnit, caloriesPer100g, proteinGramsPer100g, carbohydrateGramsPer100g, fatGramsPer100g, fiberGramsPer100g, nutritionSource: 'IFCT 2017 and USDA FoodData Central reference values' }, create: { name, standardUnit, caloriesPer100g, proteinGramsPer100g, carbohydrateGramsPer100g, fatGramsPer100g, fiberGramsPer100g, nutritionSource: 'IFCT 2017 and USDA FoodData Central reference values' } });
  }
  for (const recipe of recipes) {
    const { ingredients: recipeIngredients, ...recipeData } = recipe;
    await prisma.recipe.upsert({
      where: { slug: recipe.slug },
      update: { ...recipeData, nutritionBasis, ingredients: { deleteMany: {}, create: recipeIngredients.map(([name, quantity, unit]) => ({ quantity, unit, ingredient: { connect: { name } } })) } },
      create: { ...recipeData, nutritionBasis, ingredients: { create: recipeIngredients.map(([name, quantity, unit]) => ({ quantity, unit, ingredient: { connect: { name } } })) } },
    });
  }
}