// Exercise library DATA (Phase 2) — the V1 catalog content, separated from persistence.
// This module holds only data (no Prisma, no generation logic). The Prisma seed imports it to
// populate the database, and the validation tests import it to exercise the engines against the
// real library. Categorization values come from exercise-taxonomy.ts.

import type {
  ConstraintSeverity,
  ConstraintType,
  ExerciseCategory,
  ExerciseLaterality,
  ExerciseMechanics,
  ExerciseStatus,
  ExperienceLevel,
  RelationType,
} from './exercise-taxonomy';

export interface LibraryExercise {
  slug: string;
  name: string;
  description: string;
  category: ExerciseCategory;
  muscleGroups: string[];
  secondaryMuscleGroups: string[];
  movementPattern: string;
  mechanics: ExerciseMechanics | null;
  laterality: ExerciseLaterality;
  equipment: string[];
  equipmentAlternatives: string[];
  locations: string[];
  difficulty: ExperienceLevel;
  suitableExperience: ExperienceLevel[];
  suitableGoals: string[];
  instructions: string[];
  estimatedMinutes: number;
  status: ExerciseStatus;
}

export interface LibraryRelation { from: string; to: string; relationType: RelationType; note?: string }
export interface LibraryConstraint { slug: string; constraintType: ConstraintType; area?: string; severity: ConstraintSeverity; note?: string }

const fromBeginner: ExperienceLevel[] = ['BEGINNER', 'INTERMEDIATE', 'ADVANCED'];
const fromIntermediate: ExperienceLevel[] = ['INTERMEDIATE', 'ADVANCED'];
const advancedOnly: ExperienceLevel[] = ['ADVANCED'];
const allGoals = ['Build muscle', 'Lose fat', 'Maintain fitness'];
const buildMaintain = ['Build muscle', 'Maintain fitness'];
const conditioningGoals = ['Lose fat', 'Maintain fitness'];

export const exerciseLibrary: LibraryExercise[] = [
  { slug: 'bodyweight-squat', name: 'Bodyweight Squat', description: 'A foundational knee-dominant lower-body movement using bodyweight only.', category: 'resistance', muscleGroups: ['quads', 'glutes'], secondaryMuscleGroups: ['hamstrings', 'core'], movementPattern: 'squat', mechanics: 'compound', laterality: 'bilateral', equipment: [], equipmentAlternatives: ['Dumbbells'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Stand with feet about shoulder width.', 'Sit hips down and keep your chest tall.', 'Drive through the whole foot to stand.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'push-up', name: 'Push-up', description: 'A horizontal pressing movement driven by chest, shoulders and triceps.', category: 'resistance', muscleGroups: ['chest', 'triceps'], secondaryMuscleGroups: ['shoulders', 'core'], movementPattern: 'horizontal-push', mechanics: 'compound', laterality: 'bilateral', equipment: [], equipmentAlternatives: ['Resistance bands'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Keep a straight line from head to heel.', 'Lower chest with elbows at a comfortable angle.', 'Press the floor away.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'split-squat', name: 'Split Squat', description: 'A single-leg knee-dominant movement that also challenges balance.', category: 'resistance', muscleGroups: ['quads', 'glutes'], secondaryMuscleGroups: ['hamstrings', 'core'], movementPattern: 'single-leg', mechanics: 'compound', laterality: 'unilateral', equipment: [], equipmentAlternatives: ['Dumbbells'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Take a comfortable staggered stance.', 'Lower the back knee under control.', 'Push through the front foot to stand.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'glute-bridge', name: 'Glute Bridge', description: 'A hip-extension movement emphasising the glutes and hamstrings.', category: 'resistance', muscleGroups: ['glutes', 'hamstrings'], secondaryMuscleGroups: ['core'], movementPattern: 'hip-hinge', mechanics: 'compound', laterality: 'bilateral', equipment: [], equipmentAlternatives: ['Dumbbells'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Lie with knees bent and feet grounded.', 'Squeeze glutes to lift hips.', 'Lower without arching your lower back.'], estimatedMinutes: 6, status: 'active' },
  { slug: 'plank', name: 'Plank', description: 'An isometric anti-extension core hold.', category: 'core', muscleGroups: ['core'], secondaryMuscleGroups: ['shoulders', 'glutes'], movementPattern: 'core', mechanics: null, laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Set elbows below shoulders.', 'Keep ribs stacked over hips.', 'Breathe steadily while holding position.'], estimatedMinutes: 5, status: 'active' },
  { slug: 'dumbbell-goblet-squat', name: 'Dumbbell Goblet Squat', description: 'A loaded squat holding a single dumbbell at the chest.', category: 'resistance', muscleGroups: ['quads', 'glutes'], secondaryMuscleGroups: ['core'], movementPattern: 'squat', mechanics: 'compound', laterality: 'bilateral', equipment: ['Dumbbells'], equipmentAlternatives: ['Barbell'], locations: ['HOME', 'GYM', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Hold one dumbbell close to your chest.', 'Squat between your hips with control.', 'Stand tall through your mid-foot.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'dumbbell-floor-press', name: 'Dumbbell Floor Press', description: 'A horizontal press performed lying on the floor.', category: 'resistance', muscleGroups: ['chest', 'triceps'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'horizontal-push', mechanics: 'compound', laterality: 'bilateral', equipment: ['Dumbbells'], equipmentAlternatives: ['Barbell', 'Resistance bands'], locations: ['HOME', 'GYM', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Lie on the floor with dumbbells over chest.', 'Lower until upper arms touch the floor.', 'Press up with wrists stacked over elbows.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'dumbbell-row', name: 'Dumbbell Row', description: 'A single-arm horizontal pull for the back and biceps.', category: 'resistance', muscleGroups: ['back', 'biceps'], secondaryMuscleGroups: ['core'], movementPattern: 'horizontal-pull', mechanics: 'compound', laterality: 'unilateral', equipment: ['Dumbbells'], equipmentAlternatives: ['Resistance bands'], locations: ['HOME', 'GYM', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Brace one hand on a stable surface.', 'Pull elbow toward your hip.', 'Lower the weight under control.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'dumbbell-rdl', name: 'Dumbbell Romanian Deadlift', description: 'A hip-hinge emphasising hamstrings and glutes.', category: 'resistance', muscleGroups: ['hamstrings', 'glutes'], secondaryMuscleGroups: ['back', 'core'], movementPattern: 'hip-hinge', mechanics: 'compound', laterality: 'bilateral', equipment: ['Dumbbells'], equipmentAlternatives: ['Barbell'], locations: ['HOME', 'GYM', 'MIXED'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Hold dumbbells close to legs.', 'Push hips back with a neutral spine.', 'Stand by squeezing glutes.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'dumbbell-shoulder-press', name: 'Dumbbell Shoulder Press', description: 'A vertical overhead press for the shoulders and triceps.', category: 'resistance', muscleGroups: ['shoulders', 'triceps'], secondaryMuscleGroups: ['core'], movementPattern: 'vertical-push', mechanics: 'compound', laterality: 'bilateral', equipment: ['Dumbbells'], equipmentAlternatives: ['Barbell'], locations: ['HOME', 'GYM', 'MIXED'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Start weights at shoulder height.', 'Press overhead without leaning back.', 'Lower slowly to the start.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'barbell-back-squat', name: 'Barbell Back Squat', description: 'A heavy bilateral squat with the barbell across the upper back.', category: 'resistance', muscleGroups: ['quads', 'glutes'], secondaryMuscleGroups: ['hamstrings', 'core', 'back'], movementPattern: 'squat', mechanics: 'compound', laterality: 'bilateral', equipment: ['Barbell'], equipmentAlternatives: ['Machines'], locations: ['GYM'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Set the bar securely across upper back.', 'Brace before sitting between your hips.', 'Stand with control and a neutral spine.'], estimatedMinutes: 9, status: 'active' },
  { slug: 'barbell-bench-press', name: 'Barbell Bench Press', description: 'A heavy horizontal press with a barbell.', category: 'resistance', muscleGroups: ['chest', 'triceps'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'horizontal-push', mechanics: 'compound', laterality: 'bilateral', equipment: ['Barbell'], equipmentAlternatives: ['Dumbbells'], locations: ['GYM'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Set shoulders firmly on the bench.', 'Lower the bar with control.', 'Press to locked-out elbows without bouncing.'], estimatedMinutes: 9, status: 'active' },
  { slug: 'lat-pulldown', name: 'Lat Pulldown', description: 'A machine vertical pull for the back and biceps.', category: 'resistance', muscleGroups: ['back', 'biceps'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'vertical-pull', mechanics: 'compound', laterality: 'bilateral', equipment: ['Machines'], equipmentAlternatives: ['Resistance bands'], locations: ['GYM'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Keep chest tall and grip comfortably.', 'Pull elbows toward your ribs.', 'Control the return overhead.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'leg-press', name: 'Leg Press', description: 'A machine-supported knee-dominant pressing movement.', category: 'resistance', muscleGroups: ['quads', 'glutes'], secondaryMuscleGroups: ['hamstrings'], movementPattern: 'squat', mechanics: 'compound', laterality: 'bilateral', equipment: ['Machines'], equipmentAlternatives: ['Barbell'], locations: ['GYM'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Set feet securely on the platform.', 'Lower only as far as you can control.', 'Press without locking knees forcefully.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'band-row', name: 'Resistance Band Row', description: 'A horizontal pull using an anchored resistance band.', category: 'resistance', muscleGroups: ['back', 'biceps'], secondaryMuscleGroups: ['core'], movementPattern: 'horizontal-pull', mechanics: 'compound', laterality: 'bilateral', equipment: ['Resistance bands'], equipmentAlternatives: ['Dumbbells'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Anchor the band securely.', 'Pull elbows toward your ribs.', 'Return slowly without shrugging.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'band-chest-press', name: 'Resistance Band Chest Press', description: 'A horizontal press using an anchored resistance band.', category: 'resistance', muscleGroups: ['chest', 'triceps'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'horizontal-push', mechanics: 'compound', laterality: 'bilateral', equipment: ['Resistance bands'], equipmentAlternatives: ['Dumbbells'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Anchor band behind your body securely.', 'Press hands forward evenly.', 'Return with a controlled stretch.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'brisk-walk-interval', name: 'Brisk Walk Intervals', description: 'A low-impact conditioning piece alternating easy and brisk walking.', category: 'cardio', muscleGroups: ['conditioning'], secondaryMuscleGroups: ['quads', 'glutes', 'calves'], movementPattern: 'conditioning', mechanics: null, laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['OUTDOOR', 'HOME', 'GYM', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: conditioningGoals, instructions: ['Walk easy for two minutes.', 'Walk briskly for one minute.', 'Repeat at a pace that allows controlled breathing.'], estimatedMinutes: 8, status: 'active' },

  // Chest / horizontal push
  { slug: 'dumbbell-bench-press', name: 'Dumbbell Bench Press', description: 'A horizontal press on a bench using dumbbells.', category: 'resistance', muscleGroups: ['chest', 'triceps'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'horizontal-push', mechanics: 'compound', laterality: 'bilateral', equipment: ['Dumbbells', 'Bench'], equipmentAlternatives: ['Barbell'], locations: ['HOME', 'GYM', 'MIXED'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Lie on a bench with a dumbbell in each hand.', 'Lower to chest level with control.', 'Press up without locking harshly.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'machine-chest-press', name: 'Machine Chest Press', description: 'A guided horizontal press on a chest-press machine.', category: 'resistance', muscleGroups: ['chest', 'triceps'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'horizontal-push', mechanics: 'compound', laterality: 'bilateral', equipment: ['Machines'], equipmentAlternatives: ['Dumbbells'], locations: ['GYM'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Set the seat so handles align with mid-chest.', 'Press forward smoothly.', 'Return under control.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'cable-chest-fly', name: 'Cable Chest Fly', description: 'A chest isolation movement using cables.', category: 'resistance', muscleGroups: ['chest'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'horizontal-push', mechanics: 'isolation', laterality: 'bilateral', equipment: ['Cable'], equipmentAlternatives: ['Resistance bands'], locations: ['GYM'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Set handles at chest height.', 'Bring hands together in a hugging arc.', 'Return with a controlled stretch.'], estimatedMinutes: 6, status: 'active' },
  { slug: 'knee-push-up', name: 'Knee Push-up', description: 'A regressed push-up from the knees.', category: 'resistance', muscleGroups: ['chest', 'triceps'], secondaryMuscleGroups: ['core'], movementPattern: 'horizontal-push', mechanics: 'compound', laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Kneel and set hands under shoulders.', 'Keep a straight line from knees to head.', 'Lower and press with control.'], estimatedMinutes: 5, status: 'active' },
  // Back / pulls
  { slug: 'barbell-row', name: 'Barbell Row', description: 'A bent-over horizontal pull with a barbell.', category: 'resistance', muscleGroups: ['back', 'biceps'], secondaryMuscleGroups: ['core'], movementPattern: 'horizontal-pull', mechanics: 'compound', laterality: 'bilateral', equipment: ['Barbell'], equipmentAlternatives: ['Dumbbells'], locations: ['GYM'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Hinge with a neutral spine.', 'Pull the bar to your lower ribs.', 'Lower under control.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'seated-cable-row', name: 'Seated Cable Row', description: 'A seated horizontal pull using a cable row station.', category: 'resistance', muscleGroups: ['back', 'biceps'], secondaryMuscleGroups: ['core'], movementPattern: 'horizontal-pull', mechanics: 'compound', laterality: 'bilateral', equipment: ['Cable'], equipmentAlternatives: ['Resistance bands'], locations: ['GYM'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Sit tall with a slight knee bend.', 'Pull the handle to your waist.', 'Return without rounding your back.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'machine-row', name: 'Machine Row', description: 'A chest-supported row on a machine.', category: 'resistance', muscleGroups: ['back', 'biceps'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'horizontal-pull', mechanics: 'compound', laterality: 'bilateral', equipment: ['Machines'], equipmentAlternatives: ['Cable'], locations: ['GYM'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Set the chest pad and grip the handles.', 'Pull elbows back toward your hips.', 'Return under control.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'pull-up', name: 'Pull-up', description: 'A bodyweight vertical pull from a bar.', category: 'resistance', muscleGroups: ['back', 'biceps'], secondaryMuscleGroups: ['core'], movementPattern: 'vertical-pull', mechanics: 'compound', laterality: 'bilateral', equipment: ['Pull-up bar'], equipmentAlternatives: ['Machines'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'ADVANCED', suitableExperience: advancedOnly, suitableGoals: buildMaintain, instructions: ['Hang with hands just outside shoulders.', 'Pull your chest toward the bar.', 'Lower all the way under control.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'band-pulldown', name: 'Resistance Band Pulldown', description: 'A vertical pull using an anchored resistance band.', category: 'resistance', muscleGroups: ['back', 'biceps'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'vertical-pull', mechanics: 'compound', laterality: 'bilateral', equipment: ['Resistance bands'], equipmentAlternatives: ['Machines'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Anchor the band overhead.', 'Pull elbows down toward your ribs.', 'Return overhead with control.'], estimatedMinutes: 6, status: 'active' },
  // Shoulders
  { slug: 'barbell-overhead-press', name: 'Barbell Overhead Press', description: 'A standing vertical press with a barbell.', category: 'resistance', muscleGroups: ['shoulders', 'triceps'], secondaryMuscleGroups: ['core'], movementPattern: 'vertical-push', mechanics: 'compound', laterality: 'bilateral', equipment: ['Barbell'], equipmentAlternatives: ['Dumbbells'], locations: ['GYM'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Start the bar at shoulder height.', 'Brace and press overhead.', 'Lower under control to the shoulders.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'pike-push-up', name: 'Pike Push-up', description: 'A bodyweight vertical press with hips raised.', category: 'resistance', muscleGroups: ['shoulders', 'triceps'], secondaryMuscleGroups: ['core'], movementPattern: 'vertical-push', mechanics: 'compound', laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Form an inverted V with hips high.', 'Lower the crown of your head toward the floor.', 'Press back up.'], estimatedMinutes: 6, status: 'active' },
  { slug: 'dumbbell-lateral-raise', name: 'Dumbbell Lateral Raise', description: 'A shoulder isolation raising dumbbells to the sides.', category: 'resistance', muscleGroups: ['shoulders'], secondaryMuscleGroups: [], movementPattern: 'shoulder-abduction', mechanics: 'isolation', laterality: 'bilateral', equipment: ['Dumbbells'], equipmentAlternatives: ['Resistance bands'], locations: ['HOME', 'GYM', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Hold dumbbells at your sides.', 'Raise to shoulder height with soft elbows.', 'Lower slowly.'], estimatedMinutes: 5, status: 'active' },
  // Arms
  { slug: 'dumbbell-biceps-curl', name: 'Dumbbell Biceps Curl', description: 'An elbow-flexion isolation with dumbbells.', category: 'resistance', muscleGroups: ['biceps'], secondaryMuscleGroups: [], movementPattern: 'elbow-flexion', mechanics: 'isolation', laterality: 'bilateral', equipment: ['Dumbbells'], equipmentAlternatives: ['Resistance bands'], locations: ['HOME', 'GYM', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Hold dumbbells with palms forward.', 'Curl without swinging.', 'Lower under control.'], estimatedMinutes: 5, status: 'active' },
  { slug: 'band-biceps-curl', name: 'Resistance Band Biceps Curl', description: 'An elbow-flexion isolation using a band.', category: 'resistance', muscleGroups: ['biceps'], secondaryMuscleGroups: [], movementPattern: 'elbow-flexion', mechanics: 'isolation', laterality: 'bilateral', equipment: ['Resistance bands'], equipmentAlternatives: ['Dumbbells'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Stand on the band and hold the ends.', 'Curl toward your shoulders.', 'Lower with control.'], estimatedMinutes: 5, status: 'active' },
  { slug: 'triceps-dip', name: 'Bench Triceps Dip', description: 'An elbow-extension movement using a bench.', category: 'resistance', muscleGroups: ['triceps'], secondaryMuscleGroups: ['chest', 'shoulders'], movementPattern: 'elbow-extension', mechanics: 'compound', laterality: 'bilateral', equipment: ['Bench'], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Hands on a bench behind you.', 'Lower by bending the elbows.', 'Press back up.'], estimatedMinutes: 5, status: 'active' },
  { slug: 'cable-triceps-pushdown', name: 'Cable Triceps Pushdown', description: 'An elbow-extension isolation on a cable.', category: 'resistance', muscleGroups: ['triceps'], secondaryMuscleGroups: [], movementPattern: 'elbow-extension', mechanics: 'isolation', laterality: 'bilateral', equipment: ['Cable'], equipmentAlternatives: ['Resistance bands'], locations: ['GYM'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Grip the bar at chest height.', 'Extend the elbows down.', 'Return under control.'], estimatedMinutes: 5, status: 'active' },
  // Legs — squat / single-leg / knee
  { slug: 'bodyweight-lunge', name: 'Bodyweight Lunge', description: 'A single-leg movement stepping forward or back.', category: 'resistance', muscleGroups: ['quads', 'glutes'], secondaryMuscleGroups: ['hamstrings', 'core'], movementPattern: 'single-leg', mechanics: 'compound', laterality: 'unilateral', equipment: [], equipmentAlternatives: ['Dumbbells'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Step into a comfortable lunge.', 'Lower the back knee under control.', 'Drive back to standing.'], estimatedMinutes: 6, status: 'active' },
  { slug: 'dumbbell-walking-lunge', name: 'Dumbbell Walking Lunge', description: 'A loaded travelling single-leg movement.', category: 'resistance', muscleGroups: ['quads', 'glutes'], secondaryMuscleGroups: ['hamstrings', 'core'], movementPattern: 'single-leg', mechanics: 'compound', laterality: 'unilateral', equipment: ['Dumbbells'], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Hold dumbbells at your sides.', 'Step forward into a lunge.', 'Alternate legs with control.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'front-squat', name: 'Barbell Front Squat', description: 'A barbell squat with the bar racked on the front of the shoulders.', category: 'resistance', muscleGroups: ['quads', 'glutes'], secondaryMuscleGroups: ['core', 'back'], movementPattern: 'squat', mechanics: 'compound', laterality: 'bilateral', equipment: ['Barbell'], equipmentAlternatives: ['Dumbbells'], locations: ['GYM'], difficulty: 'ADVANCED', suitableExperience: advancedOnly, suitableGoals: buildMaintain, instructions: ['Rack the bar on the front of the shoulders.', 'Squat with an upright torso.', 'Drive up through mid-foot.'], estimatedMinutes: 9, status: 'active' },
  { slug: 'leg-extension-machine', name: 'Leg Extension', description: 'A knee-extension isolation on a machine.', category: 'resistance', muscleGroups: ['quads'], secondaryMuscleGroups: [], movementPattern: 'knee-extension', mechanics: 'isolation', laterality: 'bilateral', equipment: ['Machines'], equipmentAlternatives: [], locations: ['GYM'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Set the pad above your ankles.', 'Straighten the knees smoothly.', 'Lower under control.'], estimatedMinutes: 5, status: 'active' },
  { slug: 'wall-sit', name: 'Wall Sit', description: 'An isometric knee-dominant hold against a wall.', category: 'resistance', muscleGroups: ['quads'], secondaryMuscleGroups: ['glutes'], movementPattern: 'knee-extension', mechanics: null, laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Slide down a wall to a seated angle.', 'Keep knees over ankles.', 'Hold and breathe steadily.'], estimatedMinutes: 5, status: 'active' },
  // Legs — hinge / hamstring / hip extension
  { slug: 'barbell-rdl', name: 'Barbell Romanian Deadlift', description: 'A barbell hip-hinge emphasising hamstrings and glutes.', category: 'resistance', muscleGroups: ['hamstrings', 'glutes'], secondaryMuscleGroups: ['back', 'core'], movementPattern: 'hip-hinge', mechanics: 'compound', laterality: 'bilateral', equipment: ['Barbell'], equipmentAlternatives: ['Dumbbells'], locations: ['GYM'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Hold the bar at the hips.', 'Push hips back with a neutral spine.', 'Stand by squeezing glutes.'], estimatedMinutes: 9, status: 'active' },
  { slug: 'barbell-deadlift', name: 'Barbell Deadlift', description: 'A barbell hinge lifting the bar from the floor.', category: 'resistance', muscleGroups: ['hamstrings', 'glutes', 'back'], secondaryMuscleGroups: ['core'], movementPattern: 'hip-hinge', mechanics: 'compound', laterality: 'bilateral', equipment: ['Barbell'], equipmentAlternatives: [], locations: ['GYM'], difficulty: 'ADVANCED', suitableExperience: advancedOnly, suitableGoals: buildMaintain, instructions: ['Set up with the bar over mid-foot.', 'Brace and drive the floor away.', 'Lower with a controlled hinge.'], estimatedMinutes: 10, status: 'active' },
  { slug: 'hip-thrust', name: 'Barbell Hip Thrust', description: 'A loaded hip-extension with shoulders on a bench.', category: 'resistance', muscleGroups: ['glutes', 'hamstrings'], secondaryMuscleGroups: ['core'], movementPattern: 'hip-extension', mechanics: 'compound', laterality: 'bilateral', equipment: ['Barbell', 'Bench'], equipmentAlternatives: ['Dumbbells'], locations: ['GYM'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: buildMaintain, instructions: ['Rest shoulders on a bench with the bar at the hips.', 'Drive hips up to a straight line.', 'Lower under control.'], estimatedMinutes: 8, status: 'active' },
  { slug: 'lying-leg-curl-machine', name: 'Lying Leg Curl', description: 'A knee-flexion isolation on a machine.', category: 'resistance', muscleGroups: ['hamstrings'], secondaryMuscleGroups: [], movementPattern: 'knee-flexion', mechanics: 'isolation', laterality: 'bilateral', equipment: ['Machines'], equipmentAlternatives: [], locations: ['GYM'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Set the pad above your heels.', 'Curl the heels toward your glutes.', 'Lower under control.'], estimatedMinutes: 5, status: 'active' },
  // Calves
  { slug: 'standing-calf-raise', name: 'Standing Calf Raise', description: 'A calf movement rising onto the toes.', category: 'resistance', muscleGroups: ['calves'], secondaryMuscleGroups: [], movementPattern: 'calf', mechanics: 'isolation', laterality: 'bilateral', equipment: [], equipmentAlternatives: ['Dumbbells'], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: buildMaintain, instructions: ['Stand tall, optionally on a step.', 'Rise onto the balls of your feet.', 'Lower slowly for a full stretch.'], estimatedMinutes: 4, status: 'active' },
  // Core
  { slug: 'dead-bug', name: 'Dead Bug', description: 'An anti-extension core exercise lying on the back.', category: 'core', muscleGroups: ['core'], secondaryMuscleGroups: [], movementPattern: 'anti-extension', mechanics: 'isolation', laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Lie on your back, arms and knees up.', 'Lower an opposite arm and leg.', 'Keep your lower back flat.'], estimatedMinutes: 5, status: 'active' },
  { slug: 'side-plank', name: 'Side Plank', description: 'An anti-lateral-flexion core hold on one side.', category: 'core', muscleGroups: ['core'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'anti-lateral-flexion', mechanics: null, laterality: 'unilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Stack your body on one forearm.', 'Lift hips to a straight line.', 'Hold, then switch sides.'], estimatedMinutes: 5, status: 'active' },
  { slug: 'pallof-press', name: 'Cable Pallof Press', description: 'An anti-rotation core press using a cable.', category: 'core', muscleGroups: ['core'], secondaryMuscleGroups: ['shoulders'], movementPattern: 'anti-rotation', mechanics: 'isolation', laterality: 'bilateral', equipment: ['Cable'], equipmentAlternatives: ['Resistance bands'], locations: ['GYM'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: allGoals, instructions: ['Stand side-on to the anchor.', 'Press the handle straight out.', 'Resist rotation, then return.'], estimatedMinutes: 5, status: 'active' },
  { slug: 'bicycle-crunch', name: 'Bicycle Crunch', description: 'A trunk-flexion core movement with alternating knees.', category: 'core', muscleGroups: ['core'], secondaryMuscleGroups: [], movementPattern: 'trunk-flexion', mechanics: 'isolation', laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Lie on your back, hands by your head.', 'Bring opposite elbow and knee together.', 'Alternate smoothly without pulling the neck.'], estimatedMinutes: 5, status: 'active' },
  // Mobility
  { slug: 'cat-cow', name: 'Cat-Cow', description: 'A spinal mobility drill alternating flexion and extension.', category: 'mobility', muscleGroups: ['core', 'back'], secondaryMuscleGroups: [], movementPattern: 'thoracic-mobility', mechanics: null, laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Start on hands and knees.', 'Alternate rounding and arching the spine.', 'Move slowly with your breath.'], estimatedMinutes: 4, status: 'active' },
  { slug: 'hip-flexor-stretch', name: 'Half-Kneeling Hip Flexor Stretch', description: 'A mobility drill for the front of the hip.', category: 'mobility', muscleGroups: ['hip'], secondaryMuscleGroups: ['glutes'], movementPattern: 'hip-mobility', mechanics: null, laterality: 'unilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Kneel in a half-kneeling position.', 'Gently shift your hips forward.', 'Hold a comfortable stretch and switch sides.'], estimatedMinutes: 4, status: 'active' },
  { slug: 'band-shoulder-dislocate', name: 'Band Shoulder Pass-Through', description: 'A shoulder mobility drill with a band.', category: 'mobility', muscleGroups: ['shoulders'], secondaryMuscleGroups: [], movementPattern: 'shoulder-mobility', mechanics: null, laterality: 'bilateral', equipment: ['Resistance bands'], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: allGoals, instructions: ['Hold a band wider than shoulder width.', 'Pass it overhead and behind you.', 'Keep arms straight and move only as far as comfortable.'], estimatedMinutes: 4, status: 'active' },
  // Cardio / conditioning
  { slug: 'jumping-jacks', name: 'Jumping Jacks', description: 'A full-body conditioning movement.', category: 'conditioning', muscleGroups: ['conditioning'], secondaryMuscleGroups: ['calves', 'shoulders'], movementPattern: 'conditioning', mechanics: null, laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: conditioningGoals, instructions: ['Jump feet out while raising arms.', 'Return to standing.', 'Keep a steady rhythm.'], estimatedMinutes: 6, status: 'active' },
  { slug: 'mountain-climbers', name: 'Mountain Climbers', description: 'A floor-based conditioning movement for the whole body.', category: 'conditioning', muscleGroups: ['conditioning'], secondaryMuscleGroups: ['core', 'quads'], movementPattern: 'conditioning', mechanics: null, laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: conditioningGoals, instructions: ['Start in a push-up position.', 'Drive knees toward your chest alternately.', 'Keep hips low and steady.'], estimatedMinutes: 6, status: 'active' },
  { slug: 'burpees', name: 'Burpees', description: 'A high-intensity full-body conditioning movement.', category: 'conditioning', muscleGroups: ['conditioning'], secondaryMuscleGroups: ['chest', 'quads', 'core'], movementPattern: 'conditioning', mechanics: null, laterality: 'bilateral', equipment: [], equipmentAlternatives: [], locations: ['HOME', 'GYM', 'OUTDOOR', 'MIXED'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: conditioningGoals, instructions: ['Squat and place your hands down.', 'Jump or step back to a plank.', 'Return and jump up.'], estimatedMinutes: 7, status: 'active' },
  { slug: 'stationary-bike-intervals', name: 'Stationary Bike Intervals', description: 'A low-impact cardio interval piece on a bike.', category: 'cardio', muscleGroups: ['conditioning'], secondaryMuscleGroups: ['quads', 'glutes'], movementPattern: 'conditioning', mechanics: null, laterality: 'bilateral', equipment: ['Cardio machine'], equipmentAlternatives: [], locations: ['GYM', 'HOME', 'MIXED'], difficulty: 'BEGINNER', suitableExperience: fromBeginner, suitableGoals: conditioningGoals, instructions: ['Warm up at an easy pace.', 'Alternate harder and easier efforts.', 'Keep cadence smooth and controlled.'], estimatedMinutes: 10, status: 'active' },
  { slug: 'kettlebell-swing', name: 'Kettlebell Swing', description: 'A ballistic hip-hinge conditioning movement.', category: 'conditioning', muscleGroups: ['glutes', 'hamstrings'], secondaryMuscleGroups: ['core', 'back'], movementPattern: 'hip-hinge', mechanics: 'compound', laterality: 'bilateral', equipment: ['Kettlebell'], equipmentAlternatives: ['Dumbbells'], locations: ['HOME', 'GYM', 'MIXED'], difficulty: 'INTERMEDIATE', suitableExperience: fromIntermediate, suitableGoals: allGoals, instructions: ['Hinge and hike the bell back.', 'Snap the hips to float the bell.', 'Let it fall and repeat with rhythm.'], estimatedMinutes: 7, status: 'active' },
];

export const exerciseRelations: LibraryRelation[] = [
  { from: 'bodyweight-squat', to: 'split-squat', relationType: 'variation', note: 'Single-leg variation of the squat pattern.' },
  { from: 'split-squat', to: 'bodyweight-squat', relationType: 'easier', note: 'Bilateral regression with lower balance demand.' },
  { from: 'bodyweight-squat', to: 'dumbbell-goblet-squat', relationType: 'harder', note: 'Add external load to the same pattern.' },
  { from: 'dumbbell-goblet-squat', to: 'barbell-back-squat', relationType: 'harder', note: 'Progress to barbell loading.' },
  { from: 'dumbbell-goblet-squat', to: 'leg-press', relationType: 'alternative-same-pattern', note: 'Machine-supported squat alternative.' },
  { from: 'bodyweight-squat', to: 'leg-press', relationType: 'alternative-different-equipment' },
  { from: 'push-up', to: 'dumbbell-floor-press', relationType: 'alternative-same-pattern' },
  { from: 'push-up', to: 'band-chest-press', relationType: 'alternative-different-equipment' },
  { from: 'dumbbell-floor-press', to: 'barbell-bench-press', relationType: 'harder' },
  { from: 'band-chest-press', to: 'dumbbell-floor-press', relationType: 'alternative-different-equipment' },
  { from: 'dumbbell-row', to: 'band-row', relationType: 'alternative-different-equipment' },
  { from: 'band-row', to: 'dumbbell-row', relationType: 'alternative-different-equipment' },
  { from: 'dumbbell-row', to: 'lat-pulldown', relationType: 'alternative-similar-emphasis', note: 'Shifts emphasis toward a vertical pull.' },
  { from: 'glute-bridge', to: 'dumbbell-rdl', relationType: 'harder', note: 'Loaded hip-hinge progression.' },
  { from: 'dumbbell-rdl', to: 'glute-bridge', relationType: 'easier' },
  { from: 'barbell-bench-press', to: 'dumbbell-bench-press', relationType: 'alternative-same-pattern' },
  { from: 'barbell-bench-press', to: 'machine-chest-press', relationType: 'alternative-same-pattern' },
  { from: 'barbell-bench-press', to: 'push-up', relationType: 'alternative-different-equipment', note: 'Bodyweight horizontal press.' },
  { from: 'dumbbell-bench-press', to: 'dumbbell-floor-press', relationType: 'alternative-same-pattern' },
  { from: 'dumbbell-bench-press', to: 'barbell-bench-press', relationType: 'harder' },
  { from: 'push-up', to: 'knee-push-up', relationType: 'easier' },
  { from: 'push-up', to: 'dumbbell-bench-press', relationType: 'harder' },
  { from: 'cable-chest-fly', to: 'band-chest-press', relationType: 'alternative-different-equipment' },
  { from: 'barbell-row', to: 'dumbbell-row', relationType: 'alternative-same-pattern' },
  { from: 'barbell-row', to: 'seated-cable-row', relationType: 'alternative-same-pattern' },
  { from: 'barbell-row', to: 'machine-row', relationType: 'alternative-same-pattern' },
  { from: 'machine-row', to: 'band-row', relationType: 'alternative-different-equipment' },
  { from: 'pull-up', to: 'lat-pulldown', relationType: 'easier', note: 'Supported vertical pull.' },
  { from: 'pull-up', to: 'band-pulldown', relationType: 'easier' },
  { from: 'lat-pulldown', to: 'band-pulldown', relationType: 'alternative-different-equipment' },
  { from: 'dumbbell-shoulder-press', to: 'barbell-overhead-press', relationType: 'harder' },
  { from: 'dumbbell-shoulder-press', to: 'pike-push-up', relationType: 'alternative-different-equipment' },
  { from: 'dumbbell-shoulder-press', to: 'machine-chest-press', relationType: 'alternative-similar-emphasis' },
  { from: 'dumbbell-biceps-curl', to: 'band-biceps-curl', relationType: 'alternative-different-equipment' },
  { from: 'cable-triceps-pushdown', to: 'triceps-dip', relationType: 'alternative-different-equipment' },
  { from: 'bodyweight-squat', to: 'bodyweight-lunge', relationType: 'variation' },
  { from: 'split-squat', to: 'dumbbell-walking-lunge', relationType: 'harder' },
  { from: 'barbell-back-squat', to: 'front-squat', relationType: 'variation' },
  { from: 'leg-press', to: 'leg-extension-machine', relationType: 'alternative-similar-emphasis' },
  { from: 'dumbbell-rdl', to: 'barbell-rdl', relationType: 'harder' },
  { from: 'barbell-rdl', to: 'barbell-deadlift', relationType: 'harder' },
  { from: 'glute-bridge', to: 'hip-thrust', relationType: 'harder' },
  { from: 'dumbbell-rdl', to: 'lying-leg-curl-machine', relationType: 'alternative-similar-emphasis' },
  { from: 'kettlebell-swing', to: 'dumbbell-rdl', relationType: 'alternative-similar-emphasis' },
  { from: 'plank', to: 'dead-bug', relationType: 'alternative-similar-emphasis' },
  { from: 'plank', to: 'side-plank', relationType: 'variation' },
  { from: 'brisk-walk-interval', to: 'stationary-bike-intervals', relationType: 'alternative-different-equipment' },
  { from: 'jumping-jacks', to: 'mountain-climbers', relationType: 'alternative-same-pattern' },
  { from: 'mountain-climbers', to: 'burpees', relationType: 'harder' },
];

export const exerciseConstraints: LibraryConstraint[] = [
  { slug: 'bodyweight-squat', constraintType: 'joint-load', area: 'knee', severity: 'low' },
  { slug: 'split-squat', constraintType: 'balance-demand', severity: 'moderate' },
  { slug: 'split-squat', constraintType: 'joint-load', area: 'knee', severity: 'moderate' },
  { slug: 'glute-bridge', constraintType: 'spinal-load', area: 'lower-back', severity: 'low' },
  { slug: 'push-up', constraintType: 'joint-load', area: 'wrist', severity: 'low' },
  { slug: 'push-up', constraintType: 'joint-load', area: 'shoulder', severity: 'low' },
  { slug: 'plank', constraintType: 'spinal-load', area: 'lower-back', severity: 'low' },
  { slug: 'plank', constraintType: 'joint-load', area: 'shoulder', severity: 'low' },
  { slug: 'dumbbell-goblet-squat', constraintType: 'joint-load', area: 'knee', severity: 'moderate' },
  { slug: 'dumbbell-floor-press', constraintType: 'joint-load', area: 'shoulder', severity: 'low' },
  { slug: 'dumbbell-row', constraintType: 'spinal-load', area: 'lower-back', severity: 'low' },
  { slug: 'dumbbell-rdl', constraintType: 'spinal-load', area: 'lower-back', severity: 'moderate' },
  { slug: 'dumbbell-rdl', constraintType: 'technical-demand', severity: 'moderate', note: 'Requires a controlled hip hinge with a neutral spine.' },
  { slug: 'dumbbell-shoulder-press', constraintType: 'joint-load', area: 'shoulder', severity: 'moderate' },
  { slug: 'dumbbell-shoulder-press', constraintType: 'spinal-load', area: 'lower-back', severity: 'low' },
  { slug: 'barbell-back-squat', constraintType: 'joint-load', area: 'knee', severity: 'moderate' },
  { slug: 'barbell-back-squat', constraintType: 'spinal-load', area: 'lower-back', severity: 'moderate' },
  { slug: 'barbell-back-squat', constraintType: 'technical-demand', severity: 'high', note: 'Benefits from coaching on setup and bracing.' },
  { slug: 'barbell-bench-press', constraintType: 'joint-load', area: 'shoulder', severity: 'moderate' },
  { slug: 'barbell-bench-press', constraintType: 'technical-demand', severity: 'moderate' },
  { slug: 'lat-pulldown', constraintType: 'joint-load', area: 'shoulder', severity: 'low' },
  { slug: 'leg-press', constraintType: 'joint-load', area: 'knee', severity: 'moderate' },
  { slug: 'leg-press', constraintType: 'spinal-load', area: 'lower-back', severity: 'low' },
  { slug: 'band-chest-press', constraintType: 'joint-load', area: 'shoulder', severity: 'low' },
  { slug: 'brisk-walk-interval', constraintType: 'impact', area: 'knee', severity: 'low' },
  { slug: 'brisk-walk-interval', constraintType: 'impact', area: 'ankle', severity: 'low' },
  { slug: 'dumbbell-bench-press', constraintType: 'joint-load', area: 'shoulder', severity: 'moderate' },
  { slug: 'machine-chest-press', constraintType: 'joint-load', area: 'shoulder', severity: 'low' },
  { slug: 'cable-chest-fly', constraintType: 'joint-load', area: 'shoulder', severity: 'moderate' },
  { slug: 'barbell-row', constraintType: 'spinal-load', area: 'lower-back', severity: 'moderate' },
  { slug: 'pull-up', constraintType: 'joint-load', area: 'shoulder', severity: 'moderate' },
  { slug: 'pull-up', constraintType: 'technical-demand', severity: 'moderate' },
  { slug: 'barbell-overhead-press', constraintType: 'joint-load', area: 'shoulder', severity: 'moderate' },
  { slug: 'barbell-overhead-press', constraintType: 'spinal-load', area: 'lower-back', severity: 'low' },
  { slug: 'pike-push-up', constraintType: 'joint-load', area: 'shoulder', severity: 'moderate' },
  { slug: 'pike-push-up', constraintType: 'joint-load', area: 'wrist', severity: 'low' },
  { slug: 'triceps-dip', constraintType: 'joint-load', area: 'shoulder', severity: 'moderate' },
  { slug: 'bodyweight-lunge', constraintType: 'joint-load', area: 'knee', severity: 'moderate' },
  { slug: 'bodyweight-lunge', constraintType: 'balance-demand', severity: 'moderate' },
  { slug: 'dumbbell-walking-lunge', constraintType: 'joint-load', area: 'knee', severity: 'moderate' },
  { slug: 'dumbbell-walking-lunge', constraintType: 'balance-demand', severity: 'moderate' },
  { slug: 'front-squat', constraintType: 'joint-load', area: 'knee', severity: 'moderate' },
  { slug: 'front-squat', constraintType: 'spinal-load', area: 'lower-back', severity: 'moderate' },
  { slug: 'front-squat', constraintType: 'technical-demand', severity: 'high' },
  { slug: 'leg-extension-machine', constraintType: 'joint-load', area: 'knee', severity: 'low' },
  { slug: 'wall-sit', constraintType: 'joint-load', area: 'knee', severity: 'low' },
  { slug: 'barbell-rdl', constraintType: 'spinal-load', area: 'lower-back', severity: 'moderate' },
  { slug: 'barbell-rdl', constraintType: 'technical-demand', severity: 'moderate' },
  { slug: 'barbell-deadlift', constraintType: 'spinal-load', area: 'lower-back', severity: 'high' },
  { slug: 'barbell-deadlift', constraintType: 'technical-demand', severity: 'high' },
  { slug: 'hip-thrust', constraintType: 'spinal-load', area: 'lower-back', severity: 'low' },
  { slug: 'side-plank', constraintType: 'joint-load', area: 'shoulder', severity: 'low' },
  { slug: 'jumping-jacks', constraintType: 'impact', area: 'knee', severity: 'low' },
  { slug: 'jumping-jacks', constraintType: 'impact', area: 'ankle', severity: 'low' },
  { slug: 'mountain-climbers', constraintType: 'joint-load', area: 'wrist', severity: 'low' },
  { slug: 'burpees', constraintType: 'impact', area: 'knee', severity: 'moderate' },
  { slug: 'burpees', constraintType: 'impact', area: 'ankle', severity: 'moderate' },
  { slug: 'kettlebell-swing', constraintType: 'spinal-load', area: 'lower-back', severity: 'moderate' },
  { slug: 'kettlebell-swing', constraintType: 'technical-demand', severity: 'moderate' },
];
