import type { Questionnaire } from './types';

// Sentinel values reused across questions so the engine can treat them uniformly.
export const SKIP = '__skip__';
export const UNKNOWN = '__unknown__';
export const PREFER_NOT = '__prefer_not__';

const weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

// Schema version is persisted with each response set so future migrations can adapt old data.
export const ONBOARDING_SCHEMA_VERSION = 1;

export const questionnaire: Questionnaire = {
  version: ONBOARDING_SCHEMA_VERSION,
  sections: [
    {
      id: 'core',
      title: 'About you',
      subtitle: 'The essentials we build everything else around.',
      category: 'core',
      questions: [
        { id: 'age', kind: 'number', label: 'Age', unit: 'years', validation: { min: 13, max: 100, message: 'Enter an age between 13 and 100.' } },
        {
          id: 'sex',
          kind: 'single',
          label: 'Sex',
          help: 'Used for body-composition context only.',
          options: [
            { value: 'FEMALE', label: 'Female' },
            { value: 'MALE', label: 'Male' },
            { value: 'NON_BINARY', label: 'Non-binary' },
            { value: 'PREFER_NOT_TO_SAY', label: 'Prefer not to say' },
          ],
        },
        { id: 'heightCm', kind: 'number', label: 'Height', unit: 'cm', validation: { min: 100, max: 250, message: 'Enter a height between 100 and 250 cm.' } },
        { id: 'weightKg', kind: 'number', label: 'Weight', unit: 'kg', validation: { min: 25, max: 350, message: 'Enter a weight between 25 and 350 kg.' } },
      ],
    },
    {
      id: 'body',
      title: 'Your physique',
      subtitle: 'Only share what you know — every field here is optional.',
      category: 'body',
      questions: [
        {
          id: 'physique',
          kind: 'single',
          label: 'How would you describe your current body?',
          optional: true,
          allowSkip: true,
          skipLabel: 'Not sure',
          options: [
            { value: 'lean', label: 'Lean' },
            { value: 'average', label: 'Average' },
            { value: 'softer', label: 'Softer / higher body fat' },
            { value: 'muscular', label: 'Muscular' },
            { value: 'athletic', label: 'Athletic' },
          ],
        },
        { id: 'waistCm', kind: 'number', label: 'Waist measurement', unit: 'cm', optional: true, allowSkip: true, validation: { min: 40, max: 200 } },
        {
          id: 'bodyFatKnown',
          kind: 'single',
          label: 'Do you already know your body-fat percentage?',
          optional: true,
          allowSkip: true,
          options: [
            { value: 'yes', label: 'Yes, I know it' },
            { value: UNKNOWN, label: "No / I don't know" },
          ],
        },
        { id: 'bodyFatPercent', kind: 'number', label: 'Body-fat percentage', unit: '%', optional: true, conditions: [{ questionId: 'bodyFatKnown', equals: 'yes' }], validation: { min: 3, max: 70 } },
        {
          id: 'weightTrend',
          kind: 'single',
          label: 'Recent weight trend',
          optional: true,
          allowSkip: true,
          skipLabel: "Not sure",
          options: [
            { value: 'losing', label: 'Losing weight' },
            { value: 'stable', label: 'Staying stable' },
            { value: 'gaining', label: 'Gaining weight' },
          ],
        },
        {
          id: 'trackMeasurements',
          kind: 'multi',
          label: 'Measurements you want to track (optional)',
          optional: true,
          options: [
            { value: 'chest', label: 'Chest' },
            { value: 'arms', label: 'Arms' },
            { value: 'waist', label: 'Waist' },
            { value: 'hips', label: 'Hips' },
            { value: 'thighs', label: 'Thighs' },
          ],
        },
      ],
    },
    {
      id: 'goal',
      title: 'Your goal',
      subtitle: "Pick the one that matters most right now — we'll ask what success looks like for you.",
      category: 'goal',
      questions: [
        {
          id: 'primaryGoal',
          kind: 'single',
          label: 'Primary goal',
          options: [
            { value: 'build_muscle', label: 'Build muscle' },
            { value: 'lose_fat', label: 'Lose body fat' },
            { value: 'recomp', label: 'Build muscle + lose body fat' },
            { value: 'lean_muscle', label: 'Gain lean muscle' },
            { value: 'maintain', label: 'Maintain weight & improve fitness' },
            { value: 'strength', label: 'Increase strength' },
            { value: 'endurance', label: 'Improve endurance' },
            { value: 'athletic', label: 'Improve athletic performance' },
          ],
        },
        {
          id: 'musclePriorities',
          kind: 'multi',
          label: 'Within muscle gain, what matters most?',
          optional: true,
          conditions: [{ questionId: 'primaryGoal', in: ['build_muscle', 'lean_muscle', 'recomp', 'strength'] }],
          options: [
            { value: 'size', label: 'Muscle size' },
            { value: 'strength', label: 'Strength' },
            { value: 'lean', label: 'Staying relatively lean' },
          ],
        },
        {
          id: 'fatLossPriorities',
          kind: 'multi',
          label: 'Within fat loss, what matters most?',
          optional: true,
          conditions: [{ questionId: 'primaryGoal', in: ['lose_fat', 'recomp'] }],
          options: [
            { value: 'fat_loss', label: 'Losing fat' },
            { value: 'preserve_muscle', label: 'Preserving muscle' },
            { value: 'definition', label: 'Improving body definition' },
            { value: 'fitness', label: 'Improving fitness' },
          ],
        },
        {
          id: 'recompBalance',
          kind: 'single',
          label: 'How do you want to balance the two?',
          conditions: [{ questionId: 'primaryGoal', equals: 'recomp' }],
          options: [
            { value: 'equal', label: 'Both equally important' },
            { value: 'muscle', label: 'Muscle gain is higher priority' },
            { value: 'fat', label: 'Fat loss is higher priority' },
          ],
        },
        {
          id: 'focusAreas',
          kind: 'multi',
          label: 'Areas you want to develop',
          help: 'Guides training emphasis. You cannot target fat loss to a specific area.',
          optional: true,
          options: [
            { value: 'chest', label: 'Chest' },
            { value: 'shoulders', label: 'Shoulders' },
            { value: 'back', label: 'Back' },
            { value: 'arms', label: 'Arms' },
            { value: 'core', label: 'Core' },
            { value: 'glutes', label: 'Glutes' },
            { value: 'quads', label: 'Quads' },
            { value: 'hamstrings', label: 'Hamstrings' },
            { value: 'calves', label: 'Calves' },
            { value: 'overall', label: 'Overall physique' },
          ],
        },
        {
          id: 'secondaryGoals',
          kind: 'multi',
          label: 'Secondary goals (optional)',
          optional: true,
          options: [
            { value: 'Improve strength', label: 'Improve strength' },
            { value: 'Improve endurance', label: 'Improve endurance' },
            { value: 'Improve mobility', label: 'Improve mobility' },
            { value: 'Build consistency', label: 'Build consistency' },
          ],
        },
      ],
    },
    {
      id: 'training-experience',
      title: 'Training experience',
      subtitle: "Tell us where you're starting from.",
      category: 'training',
      questions: [
        {
          id: 'trainingExperience',
          kind: 'single',
          label: 'Overall training experience',
          options: [
            { value: 'BEGINNER', label: 'Beginner', description: 'New or less than ~6 months' },
            { value: 'INTERMEDIATE', label: 'Intermediate', description: 'Consistent for 6 months to a few years' },
            { value: 'ADVANCED', label: 'Advanced', description: 'Several years of structured training' },
          ],
        },
        {
          id: 'trainingConsistency',
          kind: 'single',
          label: 'Current training consistency',
          optional: true,
          options: [
            { value: 'none', label: 'Not training currently' },
            { value: 'on_off', label: 'On and off' },
            { value: 'fairly', label: 'Fairly consistent' },
            { value: 'very', label: 'Very consistent' },
          ],
        },
        {
          id: 'trainingHistory',
          kind: 'single',
          label: 'Previous training history',
          optional: true,
          options: [
            { value: 'never', label: 'Never trained before' },
            { value: 'past', label: 'Trained in the past' },
            { value: 'current', label: 'Currently training' },
          ],
        },
        {
          id: 'resistanceFamiliarity',
          kind: 'single',
          label: 'Familiarity with resistance training',
          optional: true,
          options: [
            { value: 'none', label: 'Not familiar' },
            { value: 'some', label: 'Somewhat familiar' },
            { value: 'high', label: 'Very familiar' },
          ],
        },
      ],
    },
    {
      id: 'workout-preferences',
      title: 'Workout preferences',
      subtitle: 'What you enjoy is what you stick with.',
      category: 'preferences',
      questions: [
        {
          id: 'preferredTrainingTypes',
          kind: 'multi',
          label: 'Training types you enjoy',
          optional: true,
          options: [
            { value: 'strength', label: 'Strength training' },
            { value: 'cardio', label: 'Cardio' },
            { value: 'bodyweight', label: 'Bodyweight' },
            { value: 'hiit', label: 'HIIT' },
            { value: 'sports', label: 'Sports / conditioning' },
            { value: 'mobility', label: 'Mobility & flexibility' },
            { value: 'classes', label: 'Group classes' },
          ],
        },
        {
          id: 'cardioPreference',
          kind: 'single',
          label: 'How do you feel about cardio?',
          optional: true,
          options: [
            { value: 'love', label: 'Love it' },
            { value: 'fine', label: "It's fine" },
            { value: 'minimal', label: 'Prefer minimal' },
          ],
        },
        { id: 'enjoyedExercises', kind: 'text', label: 'Exercises or activities you enjoy', optional: true, placeholder: 'For example: squats, cycling, swimming' },
        { id: 'dislikedExercises', kind: 'text', label: 'Exercises you dislike or want to avoid', optional: true, placeholder: 'For example: burpees, running' },
      ],
    },
    {
      id: 'availability',
      title: 'Training availability',
      subtitle: 'Your real-life schedule is a hard constraint we respect.',
      category: 'training',
      questions: [
        {
          id: 'trainingDays',
          kind: 'multi',
          label: 'Which days can you realistically train?',
          options: weekdays.map((day) => ({ value: day, label: day })),
        },
        {
          id: 'workoutDurationMinutes',
          kind: 'single',
          label: 'Typical workout length',
          unit: 'min',
          options: [
            { value: '30', label: '30 min' },
            { value: '45', label: '45 min' },
            { value: '60', label: '60 min' },
            { value: '90', label: '90 min' },
          ],
        },
        {
          id: 'trainingLocation',
          kind: 'single',
          label: 'Where will you train?',
          options: [
            { value: 'HOME', label: 'Home' },
            { value: 'GYM', label: 'Full gym' },
            { value: 'OUTDOOR', label: 'Outdoors' },
            { value: 'MIXED', label: 'A mix' },
          ],
        },
        {
          id: 'homeEquipment',
          kind: 'multi',
          label: 'Equipment you have at home',
          optional: true,
          conditions: [{ questionId: 'trainingLocation', in: ['HOME', 'OUTDOOR', 'MIXED'] }],
          options: [
            { value: 'Dumbbells', label: 'Dumbbells' },
            { value: 'Resistance bands', label: 'Resistance bands' },
            { value: 'Pull-up bar', label: 'Pull-up bar' },
            { value: 'Kettlebell', label: 'Kettlebell' },
            { value: 'Bench', label: 'Bench' },
            { value: 'Yoga mat', label: 'Yoga mat' },
            { value: 'None', label: 'No equipment' },
          ],
        },
        {
          id: 'gymEquipment',
          kind: 'multi',
          label: 'What does your gym have?',
          optional: true,
          conditions: [{ questionId: 'trainingLocation', in: ['GYM', 'MIXED'] }],
          options: [
            { value: 'Free weights', label: 'Free weights' },
            { value: 'Machines', label: 'Machines' },
            { value: 'Cables', label: 'Cables' },
            { value: 'Squat rack', label: 'Squat rack' },
            { value: 'Cardio machines', label: 'Cardio machines' },
            { value: 'Everything', label: 'Everything available' },
          ],
        },
      ],
    },
    {
      id: 'lifestyle',
      title: 'Daily activity',
      subtitle: "Life outside the gym counts — don't assume training is your whole day.",
      category: 'lifestyle',
      questions: [
        {
          id: 'dailyActivity',
          kind: 'single',
          label: 'Outside of training, how active are you?',
          optional: true,
          options: [
            { value: 'SEDENTARY', label: 'Mostly sitting' },
            { value: 'LIGHTLY_ACTIVE', label: 'Some walking / standing' },
            { value: 'MODERATELY_ACTIVE', label: 'Frequently on my feet' },
            { value: 'VERY_ACTIVE', label: 'Very active / physical job' },
          ],
        },
        {
          id: 'jobType',
          kind: 'single',
          label: 'What is your typical day like?',
          optional: true,
          options: [
            { value: 'sitting', label: 'Mostly sitting' },
            { value: 'standing', label: 'Mostly standing' },
            { value: 'walking', label: 'Frequently walking' },
            { value: 'physical', label: 'Physically active job' },
          ],
        },
        {
          id: 'stepsKnown',
          kind: 'single',
          label: 'Do you track your daily steps?',
          optional: true,
          options: [
            { value: 'yes', label: 'Yes' },
            { value: UNKNOWN, label: "No / don't know" },
          ],
        },
        { id: 'dailySteps', kind: 'number', label: 'Typical daily steps', optional: true, conditions: [{ questionId: 'stepsKnown', equals: 'yes' }], validation: { min: 0, max: 60000 } },
        { id: 'otherActivities', kind: 'text', label: 'Other regular physical activities', optional: true, placeholder: 'For example: cycling to work, weekend hikes' },
      ],
    },
    {
      id: 'routine',
      title: 'Daily routine',
      subtitle: "We plan around your actual day, not a generic template.",
      category: 'lifestyle',
      questions: [
        { id: 'wakeTime', kind: 'time', label: 'Wake-up time' },
        {
          id: 'workSchedule',
          kind: 'single',
          label: 'Work or college schedule',
          options: [
            { value: 'Morning schedule', label: 'Morning' },
            { value: 'Afternoon schedule', label: 'Afternoon' },
            { value: 'Evening schedule', label: 'Evening' },
            { value: 'Rotating shifts', label: 'Rotating shifts' },
            { value: 'Flexible', label: 'Flexible' },
          ],
        },
        { id: 'preferredGymTime', kind: 'time', label: 'Preferred training time' },
        { id: 'sleepTime', kind: 'time', label: 'Sleep time' },
        {
          id: 'sleepDuration',
          kind: 'single',
          label: 'Typical sleep duration',
          optional: true,
          options: [
            { value: 'lt6', label: 'Under 6 hours' },
            { value: '6to7', label: '6–7 hours' },
            { value: '7to8', label: '7–8 hours' },
            { value: 'gt8', label: '8+ hours' },
            { value: 'varies', label: 'Varies' },
          ],
        },
      ],
    },
    {
      id: 'nutrition',
      title: 'Nutrition profile',
      subtitle: 'Preferences are different from allergies — we keep them separate.',
      category: 'nutrition',
      questions: [
        {
          id: 'dietType',
          kind: 'single',
          label: 'Diet preference',
          options: [
            { value: 'vegetarian', label: 'Vegetarian' },
            { value: 'eggetarian', label: 'Eggetarian' },
            { value: 'non_vegetarian', label: 'Non-vegetarian' },
            { value: 'vegan', label: 'Vegan' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          id: 'cookingSituation',
          kind: 'single',
          label: 'How do you usually eat?',
          optional: true,
          options: [
            { value: 'cook', label: 'I cook at home' },
            { value: 'family', label: 'Family cooks' },
            { value: 'mess', label: 'Mess / hostel' },
            { value: 'restaurants', label: 'Restaurants / takeout' },
            { value: 'meal_service', label: 'Meal service' },
          ],
        },
        {
          id: 'cookingTime',
          kind: 'single',
          label: 'Time available to cook',
          optional: true,
          conditions: [{ questionId: 'cookingSituation', in: ['cook', 'family'] }],
          options: [
            { value: 'lt15', label: 'Under 15 min' },
            { value: '15to30', label: '15–30 min' },
            { value: '30to60', label: '30–60 min' },
            { value: 'enjoy', label: 'I enjoy cooking' },
          ],
        },
        {
          id: 'foodBudget',
          kind: 'single',
          label: 'Food budget',
          optional: true,
          options: [
            { value: 'tight', label: 'Tight' },
            { value: 'moderate', label: 'Moderate' },
            { value: 'flexible', label: 'Flexible' },
          ],
        },
        {
          id: 'mealsPerDay',
          kind: 'single',
          label: 'Preferred number of meals',
          optional: true,
          options: [
            { value: '2', label: '2' },
            { value: '3', label: '3' },
            { value: '4', label: '4' },
            { value: '5', label: '5+' },
          ],
        },
        {
          id: 'preferredCuisines',
          kind: 'multi',
          label: 'Preferred cuisines',
          optional: true,
          options: [
            { value: 'north_indian', label: 'North Indian' },
            { value: 'south_indian', label: 'South Indian' },
            { value: 'continental', label: 'Continental' },
            { value: 'chinese', label: 'Chinese' },
            { value: 'mediterranean', label: 'Mediterranean' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          id: 'foodPreferences',
          kind: 'multi',
          label: 'Food style preferences',
          optional: true,
          options: [
            { value: 'High protein', label: 'High protein' },
            { value: 'Home cooked', label: 'Home cooked' },
            { value: 'Quick meals', label: 'Quick meals' },
            { value: 'Budget friendly', label: 'Budget friendly' },
          ],
        },
        { id: 'foodsRegular', kind: 'text', label: 'Foods you regularly eat', optional: true, placeholder: 'For example: rice, dal, eggs, oats' },
        { id: 'foodsLike', kind: 'text', label: 'Foods you like', optional: true },
        { id: 'foodsDislike', kind: 'text', label: 'Foods you dislike', optional: true },
        {
          id: 'dietaryRestrictions',
          kind: 'multi',
          label: 'Dietary or cultural/religious restrictions',
          optional: true,
          options: [
            { value: 'Gluten-free', label: 'Gluten-free' },
            { value: 'Dairy-free', label: 'Dairy-free' },
            { value: 'Low-carb', label: 'Low-carb' },
            { value: 'Jain', label: 'Jain' },
            { value: 'Halal', label: 'Halal' },
            { value: 'Kosher', label: 'Kosher' },
            { value: 'None', label: 'None' },
          ],
        },
        { id: 'allergies', kind: 'text', label: 'Food allergies', help: 'Kept separate from preferences for safety.', optional: true, placeholder: 'For example: peanuts, shellfish' },
        { id: 'intolerances', kind: 'text', label: 'Food intolerances', optional: true, placeholder: 'For example: lactose' },
      ],
    },
    {
      id: 'health',
      title: 'Health & safety',
      subtitle: "This keeps your plan safe. Share only what you're comfortable with.",
      category: 'health',
      questions: [
        {
          id: 'hasHealthConditions',
          kind: 'single',
          label: 'Do you have any medical conditions we should know about?',
          options: [
            { value: 'no', label: 'No, none' },
            { value: 'yes', label: 'Yes, I have some' },
            { value: PREFER_NOT, label: 'Prefer not to say' },
          ],
        },
        {
          id: 'healthConditions',
          kind: 'multi',
          label: 'Which apply?',
          help: 'We will not diagnose anything — this only helps us keep activity safe.',
          optional: true,
          conditions: [{ questionId: 'hasHealthConditions', equals: 'yes' }],
          options: [
            { value: 'heart', label: 'Heart condition' },
            { value: 'blood_pressure', label: 'High blood pressure' },
            { value: 'diabetes', label: 'Diabetes' },
            { value: 'asthma', label: 'Asthma / breathing' },
            { value: 'pregnancy', label: 'Pregnancy or postpartum' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          id: 'hasInjuries',
          kind: 'single',
          label: 'Any current or past injuries?',
          options: [
            { value: 'no', label: 'No' },
            { value: 'yes', label: 'Yes, currently' },
            { value: 'recovered', label: 'Previously, now recovered' },
          ],
        },
        {
          id: 'injuryAreas',
          kind: 'multi',
          label: 'Which areas?',
          optional: true,
          conditions: [{ questionId: 'hasInjuries', in: ['yes', 'recovered'] }],
          options: [
            { value: 'knee', label: 'Knee' },
            { value: 'shoulder', label: 'Shoulder' },
            { value: 'back', label: 'Back' },
            { value: 'neck', label: 'Neck' },
            { value: 'hip', label: 'Hip' },
            { value: 'ankle', label: 'Ankle' },
            { value: 'wrist', label: 'Wrist' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          id: 'mobilityLimitations',
          kind: 'single',
          label: 'Any mobility or physical limitations?',
          optional: true,
          conditions: [{ questionId: 'hasInjuries', in: ['yes', 'recovered'] }],
          options: [
            { value: 'none', label: 'None' },
            { value: 'some', label: 'Some limitations' },
            { value: 'significant', label: 'Significant limitations' },
          ],
        },
        {
          id: 'doctorExerciseRestrictions',
          kind: 'single',
          label: 'Has a doctor restricted your exercise?',
          options: [
            { value: 'no', label: 'No' },
            { value: 'yes', label: 'Yes' },
            { value: UNKNOWN, label: 'Not sure' },
          ],
        },
        {
          id: 'doctorDietRestrictions',
          kind: 'single',
          label: 'Has a doctor restricted your diet?',
          options: [
            { value: 'no', label: 'No' },
            { value: 'yes', label: 'Yes' },
            { value: UNKNOWN, label: 'Not sure' },
          ],
        },
        { id: 'medications', kind: 'text', label: 'Medications (optional)', help: 'Only if you choose to share.', optional: true, allowSkip: true, skipLabel: 'Prefer not to say' },
        { id: 'healthNotes', kind: 'text', label: 'Anything else that affects activity or food?', optional: true },
      ],
    },
    {
      id: 'preferences',
      title: 'Personal preferences',
      subtitle: 'These shape how your plan feels day to day.',
      category: 'preferences',
      questions: [
        {
          id: 'variety',
          kind: 'single',
          label: 'How much variety do you want?',
          optional: true,
          options: [
            { value: 'simple', label: 'Keep it simple and repeatable' },
            { value: 'some', label: 'Some variety' },
            { value: 'lots', label: 'Lots of variety' },
          ],
        },
        {
          id: 'detailLevel',
          kind: 'single',
          label: 'How detailed should your routine be?',
          optional: true,
          options: [
            { value: 'simple', label: 'Keep it simple' },
            { value: 'balanced', label: 'Balanced' },
            { value: 'detailed', label: 'Detailed and thorough' },
          ],
        },
        {
          id: 'workoutStyle',
          kind: 'single',
          label: 'Preferred workout style',
          optional: true,
          options: [
            { value: 'intense', label: 'Short and intense' },
            { value: 'moderate', label: 'Steady and moderate' },
            { value: 'relaxed', label: 'Relaxed pace' },
          ],
        },
        { id: 'strongDislikes', kind: 'text', label: 'Anything you strongly dislike or want to avoid?', optional: true },
      ],
    },
  ],
};
