import type { Profile } from '@/types/fitness';

export function Dashboard({ profile, mealDone, onWorkout, onMeal }: { profile: Profile; mealDone: boolean; onWorkout: () => void; onMeal: () => void }) {
  return <>
    <div className="topbar"><span className="eyebrow">Thursday · September 10, 2026</span><span className="date">Week 06 of 12</span></div>
    <section className="greeting"><div><span className="eyebrow">Good evening, {profile.name}</span><h1>Make today count<br /><em>without overthinking it.</em></h1></div><div className="streak"><strong>06</strong><span>day consistency streak</span></div></section>
    <section className="grid"><article className="card workout-card"><div className="card-title"><span className="micro">Today's workout · 07:00 PM</span><span className="micro">52 min</span></div><div className="workout-name">Upper<br />strength</div><div className="subtle">5 exercises · 15 working sets</div><div className="workout-footer"><span className="subtle">Focus: chest · back · shoulders</span><button className="primary" onClick={onWorkout}>Start workout&nbsp; ↗</button></div></article>
      <div><article className="card nutrition"><div className="card-title"><h2>Fuel for today</h2><span className="micro">82% on track</span></div><div className="macro-total">1,820 <span>/ 2,400 kcal</span></div><div className="progress-bar"><i style={{ width: '76%' }} /></div>{[['Protein', '112 / 160 g'], ['Carbs', '218 / 300 g'], ['Fats', '48 / 75 g']].map(([name, value]) => <div className="macro-row" key={name}><span>{name}</span><b>{value}</b></div>)}</article>
        <article className="card next-meal"><div className="card-title"><span className="micro">Next meal · 08:30 PM</span><span>↗</span></div><div className="meal-title">Paneer rice bowl</div><div className="meal-info"><span><b>520 kcal</b>energy</span><span><b>28g</b>protein</span><span><b>20 min</b>prep time</span></div><button className="outline" style={{ marginTop: 21 }} onClick={onMeal}>{mealDone ? '✓ Logged for today' : 'View meal'}</button></article></div></section>
    <section className="lower-grid"><article className="card schedule"><div className="card-title"><h2>Your rhythm</h2><span className="micro">Today</span></div><div className="schedule-list">{[['07:30 AM', 'Breakfast'], ['01:00 PM', 'Lunch'], ['07:00 PM', 'Workout'], ['08:30 PM', 'Dinner'], ['11:00 PM', 'Sleep']].map(([time, label], index) => <div className={`schedule-item ${index === 2 ? 'current' : ''}`} key={time}><span>{time}</span>{label}{index === 2 && <b>now</b>}</div>)}</div></article><article className="card"><div className="card-title"><h2>Keep the momentum</h2><span className="micro">This week</span></div><div className="goal-row"><div className="goal-ring"><strong>82%</strong></div><div className="goal-copy"><h3>You're building a habit.</h3><p>3 of 4 workouts complete.<br />One focused session left.</p></div></div><div className="bars">{[48, 70, 85, 35, 60, 90, 20].map((height, index) => <i style={{ height: `${height}%` }} key={index} />)}</div><div className="bar-labels">{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((day, index) => <span key={`${day}-${index}`}>{day}</span>)}</div></article></section>
  </>;
}
