import type { Profile, Modal } from '@/types/fitness';

interface ModalProps { type: Modal; profile: Profile; step: number; done: number[]; mealDone: boolean; onClose: () => void; onToggle: (index: number) => void; onComplete: () => void; onMeal: () => void; onNext: () => void; onProfile: (profile: Profile) => void; }
export function Modal({ type, profile, step, done, mealDone, onClose, onToggle, onComplete, onMeal, onNext, onProfile }: ModalProps) {
  if (!type) return null;
  if (type === 'workout') return <div className="modal-backdrop"><div className="modal"><ModalHead title="Your generated session" eyebrow="Today's workout" copy="Your plan is based on your schedule, experience, location, and available equipment." onClose={onClose} /><p className="subtle">Open the Workout plan to view and log your generated exercises.</p><div className="modal-footer"><button className="primary" onClick={onClose}>View workout plan</button></div></div></div>;
  if (type === 'meal') return <div className="modal-backdrop"><div className="modal"><ModalHead title="Paneer rice bowl" eyebrow="Dinner · 08:30 PM" copy="A balanced, high-protein dinner built around your targets." onClose={onClose} /><div className="meal-info" style={{ margin: '28px 0' }}><span><b>520 kcal</b>energy</span><span><b>28g</b>protein</span><span><b>62g</b>carbs</span><span><b>20g</b>fat</span></div><div className="schedule-list">{[['200g', 'Cooked basmati rice'], ['150g', 'Paneer, cubed'], ['100g', 'Seasonal vegetables'], ['10g', 'Olive oil & spices']].map(([amount, ingredient]) => <div className="schedule-item" key={amount}><span>{amount}</span>{ingredient}</div>)}</div><div className="modal-footer"><button className="outline" onClick={() => window.alert('Meal alternatives will preserve a similar calorie and protein target.')}>Replace meal</button><button className="primary" onClick={onMeal}>{mealDone ? 'Logged ✓' : 'I ate this'}</button></div></div></div>;
  const steps = ['Basics', 'Goal', 'Schedule', 'Food'];
  return <div className="modal-backdrop"><div className="modal"><ModalHead title="Build around your life." eyebrow={`Personal setup · Step ${step} of 4`} copy="A few details help us make your plan feel like yours." onClose={onClose} /><div className="steps">{steps.map((label, index) => <i className={index < step ? 'active' : ''} key={label} />)}</div>{step === 1 ? <div className="form-grid"><Field label="Name"><input value={profile.name} onChange={(event) => onProfile({ ...profile, name: event.target.value })} /></Field><Field label="Age"><input defaultValue="26" /></Field><Field label="Height"><input defaultValue="175 cm" /></Field><Field label="Weight"><input defaultValue="72 kg" /></Field></div> : step === 2 ? <ChoiceField label="Primary goal" values={['Build muscle', 'Lose fat', 'Maintain fitness', 'Improve strength']} selected={profile.goal} onSelect={(goal) => onProfile({ ...profile, goal })} /> : step === 3 ? <><ChoiceField label="Days you can train" values={['3 days / week', '4 days / week', '5 days / week']} selected={profile.days} onSelect={(days) => onProfile({ ...profile, days })} /><ChoiceField label="Typical session" values={['45–60 minutes', '60–90 minutes']} selected="45–60 minutes" onSelect={() => undefined} /></> : <><ChoiceField label="Diet style" values={['Vegetarian', 'Non-vegetarian', 'Vegan']} selected={profile.diet} onSelect={(diet) => onProfile({ ...profile, diet })} /><p className="subtle" style={{ marginTop: 20 }}>We use defined recipes and serving sizes so your nutrition targets stay useful, without pretending homemade food is perfectly exact.</p></>}<div className="modal-footer"><span className="micro">{step} / 4</span><button className="primary" onClick={onNext}>{step === 4 ? 'Save my plan' : 'Continue'}</button></div></div></div>;
}
function ModalHead({ eyebrow, title, copy, onClose }: { eyebrow: string; title: string; copy: string; onClose: () => void }) { return <div className="modal-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p className="subtle">{copy}</p></div><button className="close" onClick={onClose}>×</button></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="field"><label>{label}</label>{children}</div>; }
function ChoiceField({ label, values, selected, onSelect }: { label: string; values: string[]; selected: string; onSelect: (value: string) => void }) { return <div className="field" style={{ marginTop: label === 'Typical session' ? 20 : 0 }}><label>{label}</label><div className="choices">{values.map((value) => <button className={`choice ${value === selected ? 'selected' : ''}`} key={value} onClick={() => onSelect(value)}>{value}</button>)}</div></div>; }
