import type { Profile } from '@/types/fitness';

export const exercises = [['Incline dumbbell press', '3 sets  ·  8–10 reps'], ['Single-arm cable row', '3 sets  ·  10–12 reps'], ['Seated shoulder press', '3 sets  ·  8–10 reps'], ['Cable lateral raise', '3 sets  ·  12–15 reps'], ['Rope triceps extension', '2 sets  ·  12–15 reps']] as const;

export function WorkoutPage({ done, onToggle, onComplete }: { done: number[]; onToggle: (index: number) => void; onComplete: () => void }) { return <><div className="card-title"><h2>Upper strength</h2><span className="micro">52 min</span></div><div className="workout-list">{exercises.map(([name, detail], index) => <div className="exercise" key={name}><div><strong>{index + 1}. {name}</strong><span>{detail}</span></div><button className={`check ${done.includes(index) ? 'done' : ''}`} onClick={() => onToggle(index)}>{done.includes(index) ? '✓' : ''}</button></div>)}</div><button className="primary dark-button" style={{ marginTop: 22 }} onClick={onComplete}>{done.length === 5 ? 'Finish workout' : 'Log each set above'}</button></>; }
export function DietPage({ mealDone, onMeal }: { mealDone: boolean; onMeal: () => void }) { return <><div className="card-title"><h2>Thursday's meals</h2><span className="micro">2,400 kcal target</span></div><div className="schedule-list">{[['07:30 AM', 'Greek yogurt & oats', '520 kcal'], ['01:00 PM', 'Rajma quinoa bowl', '640 kcal'], ['05:30 PM', 'Banana protein shake', '280 kcal'], ['08:30 PM', 'Paneer rice bowl', '520 kcal']].map(([time, meal, kcal], index) => <div className={`schedule-item ${index === 2 ? 'current' : ''}`} key={time}><span>{time}</span>{meal}<b>{kcal}</b></div>)}</div><button className="primary dark-button" style={{ marginTop: 24 }} onClick={onMeal}>{mealDone ? 'Meal logged ✓' : 'Log next meal'}</button></>; }
export function CalendarPage() { return <><div className="card-title"><h2>September 2026</h2><span className="micro">4 workouts planned</span></div><div className="schedule-list">{[['Mon 07', 'Lower body', '✓'], ['Tue 08', 'Rest day', ''], ['Thu 10', 'Upper strength', 'Today'], ['Sat 12', 'Lower body', '']].map(([day, workout, status]) => <div className={`schedule-item ${status === 'Today' ? 'current' : ''}`} key={day}><span>{day}</span>{workout}<b>{status}</b></div>)}</div></>; }
export function ProgressPage() { return <><div className="card-title"><h2>Progress worth noticing</h2><span className="micro">Last 6 weeks</span></div><div className="goal-row"><div className="goal-ring"><strong>+8%</strong></div><div className="goal-copy"><h3>Strength is trending up.</h3><p>Bench press: 50kg → 60kg<br />Average workout: 4 / week</p></div></div><div className="bars" style={{ height: 150, marginTop: 28 }}>{[30, 48, 44, 65, 71, 86].map((height, index) => <i style={{ height: `${height}%` }} key={index} />)}</div><div className="bar-labels">{['W1', 'W2', 'W3', 'W4', 'W5', 'W6'].map((week) => <span key={week}>{week}</span>)}</div></>; }
export function ProfilePage({ profile, onEdit }: { profile: Profile; onEdit: () => void }) { return <><div className="card-title"><h2>{profile.name} Kumar</h2><span className="micro">Profile</span></div><div className="schedule-list">{[['Primary goal', profile.goal], ['Training rhythm', profile.days], ['Nutrition', profile.diet], ['Plan created', 'Aug 03, 2026']].map(([label, value]) => <div className="schedule-item" key={label}><span>{label}</span><b>{value}</b></div>)}</div><button className="primary dark-button" style={{ marginTop: 24 }} onClick={onEdit}>Update preferences</button></>; }
