import { useEffect, useState } from 'react';
import { fitnessApi } from '@/lib/api';
import type { GeneratedWorkoutPlan, Profile, ProgressSummary, ReminderSettings } from '@/types/fitness';

export function WorkoutPage({ done, onToggle, onComplete }: { done: number[]; onToggle: (index: number) => void; onComplete: () => void }) {
	const [plan, setPlan] = useState<GeneratedWorkoutPlan | null>(null);
	const [error, setError] = useState<string | null>(null);
	useEffect(() => { fitnessApi.getWorkoutPlan().then(setPlan).catch(() => setError('Complete your training setup to view your workout plan.')); }, []);
	if (error) return <p className="subtle">{error}</p>;
	if (!plan) return <p className="subtle">Building your workout plan...</p>;
	const session = plan.days[0];
	return <><div className="card-title"><div><h2>{session.title}</h2><span className="micro">{session.targetMuscleGroups.join(' · ')}</span></div><span className="micro">{session.estimatedMinutes} min</span></div><div className="workout-list">{session.exercises.map((item, index) => <div className="exercise" key={item.id}><div><strong>{index + 1}. {item.exercise.name}</strong><span>{item.sets} sets · {item.reps} reps · {item.restSeconds} sec rest</span><span>{item.exercise.instructions[0]}</span></div><button className={`check ${done.includes(index) ? 'done' : ''}`} aria-label={`Mark ${item.exercise.name} complete`} onClick={() => onToggle(index)}>{done.includes(index) ? '✓' : ''}</button></div>)}</div><button className="primary dark-button" style={{ marginTop: 22 }} onClick={onComplete}>{done.length === session.exercises.length ? 'Finish workout' : 'Log each exercise above'}</button></>;
}
export function DietPage({ mealDone, onMeal }: { mealDone: boolean; onMeal: () => void }) { return <><div className="card-title"><h2>Thursday's meals</h2><span className="micro">2,400 kcal target</span></div><div className="schedule-list">{[['07:30 AM', 'Greek yogurt & oats', '520 kcal'], ['01:00 PM', 'Rajma quinoa bowl', '640 kcal'], ['05:30 PM', 'Banana protein shake', '280 kcal'], ['08:30 PM', 'Paneer rice bowl', '520 kcal']].map(([time, meal, kcal], index) => <div className={`schedule-item ${index === 2 ? 'current' : ''}`} key={time}><span>{time}</span>{meal}<b>{kcal}</b></div>)}</div><button className="primary dark-button" style={{ marginTop: 24 }} onClick={onMeal}>{mealDone ? 'Meal logged ✓' : 'Log next meal'}</button></>; }
export function CalendarPage() { return <><div className="card-title"><h2>September 2026</h2><span className="micro">4 workouts planned</span></div><div className="schedule-list">{[['Mon 07', 'Lower body', '✓'], ['Tue 08', 'Rest day', ''], ['Thu 10', 'Upper strength', 'Today'], ['Sat 12', 'Lower body', '']].map(([day, workout, status]) => <div className={`schedule-item ${status === 'Today' ? 'current' : ''}`} key={day}><span>{day}</span>{workout}<b>{status}</b></div>)}</div></>; }
export function ProgressPage() {
	const [summary, setSummary] = useState<ProgressSummary | null>(null);
	const [weightKg, setWeightKg] = useState('');
	const [waistCm, setWaistCm] = useState('');
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const load = () => fitnessApi.getProgress().then(setSummary).catch(() => setError('Unable to load progress.'));
	useEffect(() => { load(); }, []);
	const setFrequency = async (checkInFrequencyDays: 7 | 14) => { setError(null); try { await fitnessApi.saveProgressSettings(checkInFrequencyDays); await load(); } catch { setError('Unable to save check-in frequency.'); } };
	const save = async () => { if (!weightKg || Number(weightKg) < 25 || Number(weightKg) > 350) return setError('Enter a valid weight.'); setSaving(true); setError(null); try { await fitnessApi.saveCheckIn({ recordedAt: new Date().toISOString().slice(0, 10), weightKg: Number(weightKg), measurements: waistCm ? [{ type: 'WAIST', valueCm: Number(waistCm) }] : undefined }); setWeightKg(''); setWaistCm(''); await load(); } catch { setError('Unable to save your check-in.'); } finally { setSaving(false); } };
	if (!summary) return <p className="subtle">Loading your progress...</p>;
	return <><div className="card-title"><h2>Progress check-in</h2><span className="micro">{summary.checkIn.due ? 'Due now' : `Next: ${new Date(summary.checkIn.dueDate).toLocaleDateString('en-IN')}`}</span></div>{error && <div className="api-status error">{error}</div>}<div className="form-grid"><NumberField label="Weight (kg)" value={weightKg ? Number(weightKg) : undefined} onChange={(value) => setWeightKg(value?.toString() ?? '')} /><NumberField label="Waist (cm, optional)" value={waistCm ? Number(waistCm) : undefined} onChange={(value) => setWaistCm(value?.toString() ?? '')} /></div><div className="choices" style={{ marginTop: 16 }}><button className={`choice ${summary.checkIn.frequencyDays === 7 ? 'selected' : ''}`} onClick={() => void setFrequency(7)}>Weekly</button><button className={`choice ${summary.checkIn.frequencyDays === 14 ? 'selected' : ''}`} onClick={() => void setFrequency(14)}>Every 2 weeks</button></div><button className="primary dark-button" disabled={saving} style={{ marginTop: 18 }} onClick={() => void save()}>{saving ? 'Saving...' : 'Save check-in'}</button><div className="schedule-list" style={{ marginTop: 24 }}>{summary.weightTrend.map((entry) => <div className="schedule-item" key={entry.date}><span>{new Date(entry.date).toLocaleDateString('en-IN')}</span><b>{entry.weightKg} kg</b></div>)}</div><p className="subtle">{summary.checkIn.weightChangeKg === null ? 'Your first check-in establishes a baseline.' : `${summary.checkIn.weightChangeKg > 0 ? '+' : ''}${summary.checkIn.weightChangeKg} kg since the previous check-in.`} {summary.checkIn.note}</p><div className="macro-row"><span>Workout consistency</span><b>{summary.consistency.completedWorkouts} / {summary.consistency.plannedWorkouts} ({summary.consistency.workoutCompletionPercent}%)</b></div><div className="macro-row"><span>Meal adherence</span><b>{summary.consistency.mealsCompleted} / {summary.consistency.mealsPlanned} ({summary.consistency.mealAdherencePercent}%)</b></div>{summary.performance.length > 0 && <div className="schedule-list" style={{ marginTop: 18 }}>{summary.performance.slice(0, 5).map((item, index) => <div className="schedule-item" key={`${item.exercise}-${index}`}><span>{item.exercise}</span><b>{item.sets} x {item.reps}{item.weightKg !== null ? ` · ${item.weightKg} kg` : ''}</b></div>)}</div>}</>;
}
export function ProfilePage({ profile, onEdit }: { profile: Profile; onEdit: () => void }) { return <><div className="card-title"><h2>{profile.name}</h2><span className="micro">Profile</span></div><div className="schedule-list">{[['Primary goal', profile.goal], ['Training rhythm', profile.days], ['Food preference', profile.diet]].map(([label, value]) => <div className="schedule-item" key={label}><span>{label}</span><b>{value}</b></div>)}</div><button className="primary dark-button" style={{ marginTop: 24 }} onClick={onEdit}>Update preferences</button><ReminderControls /></>; }

function ReminderControls() {
	const [settings, setSettings] = useState<ReminderSettings | null>(null);
	const [error, setError] = useState<string | null>(null);
	useEffect(() => { fitnessApi.getReminderSettings().then(setSettings).catch(() => setError('Unable to load reminder settings.')); }, []);
	const save = async (changes: Partial<ReminderSettings>) => { setError(null); try { const next = await fitnessApi.saveReminderSettings(changes); setSettings(next); } catch { setError('Unable to save reminder settings.'); } };
	if (!settings) return <p className="subtle" style={{ marginTop: 24 }}>{error ?? 'Loading reminders...'}</p>;
	const toggles: Array<[keyof Pick<ReminderSettings, 'workoutEnabled' | 'mealEnabled' | 'preWorkoutEnabled' | 'postWorkoutEnabled' | 'checkInEnabled'>, string]> = [['workoutEnabled', 'Workout'], ['mealEnabled', 'Meals'], ['preWorkoutEnabled', 'Pre-workout'], ['postWorkoutEnabled', 'Post-workout'], ['checkInEnabled', 'Progress check-in']];
	return <section style={{ marginTop: 28 }}><div className="card-title"><h2>Reminders</h2><span className="micro">No push delivery yet</span></div>{error && <div className="api-status error">{error}</div>}<div className="schedule-list">{toggles.map(([key, label]) => <label className="schedule-item" key={key}><span>{label}</span><input type="checkbox" checked={settings[key]} onChange={(event) => void save({ [key]: event.target.checked })} /></label>)}</div><div className="form-grid" style={{ marginTop: 16 }}><div className="field"><label>Timezone</label><input value={settings.timezone} onChange={(event) => setSettings({ ...settings, timezone: event.target.value })} onBlur={() => void save({ timezone: settings.timezone })} /></div><div className="field"><label>Workout reminder lead (minutes)</label><input type="number" min="5" max="120" value={settings.workoutLeadMinutes} onChange={(event) => setSettings({ ...settings, workoutLeadMinutes: Number(event.target.value) })} onBlur={() => void save({ workoutLeadMinutes: settings.workoutLeadMinutes })} /></div><div className="field"><label>Meal reminder lead (minutes)</label><input type="number" min="0" max="60" value={settings.mealLeadMinutes} onChange={(event) => setSettings({ ...settings, mealLeadMinutes: Number(event.target.value) })} onBlur={() => void save({ mealLeadMinutes: settings.mealLeadMinutes })} /></div><div className="field"><label>Check-in reminder time</label><input type="time" value={settings.checkInTime} onChange={(event) => setSettings({ ...settings, checkInTime: event.target.value })} onBlur={() => void save({ checkInTime: settings.checkInTime })} /></div></div><p className="subtle">Reminder times follow your saved schedule and timezone. This web app stores preferences and does not send push notifications.</p></section>;
}

function NumberField({ label, value, onChange }: { label: string; value?: number; onChange: (value: number | undefined) => void }) { return <div className="field"><label>{label}</label><input type="number" value={value ?? ''} onChange={(event) => onChange(event.target.value ? Number(event.target.value) : undefined)} /></div>; }
